In [4]:
######newwwwww
import math
from datetime import date
from datetime import datetime
from datetime import timedelta
import pandas as pd

In [5]:
def NYdate(jula_year):
    ny = jula_year*0.25875-int(jula_year/4 +0.5)+int(jula_year/100 +0.38)-int(jula_year/400 +0.595)-5.53375
    jultin =  ((jula_year*292207)+373)%800
    hour,frac = divmod(jultin*24,800)
    minute,frac = divmod(frac*60,800)
    second,frac = divmod(frac*60,800)
    christ_year = jula_year+638
    dtny = datetime(christ_year, 4, int(ny), hour , minute, second)
    return dtny;

In [6]:
class hora:
    def __init__(self,dt):
        offset = timedelta(minutes=18)
        dt= dt-offset
        jula_year = dt.year-638    
        d = date(dt.year,dt.month,dt.day)
        dtf= datetime(dt.year,dt.month,dt.day,0,0)        
        dtny = NYdate(jula_year)
        dny = date(dtny.year,dtny.month,dtny.day)
        
        if (dt>=dtny):
            jula_newyear = jula_year
        elif (dt<dtny):
            jula_newyear = jula_year-1
            dtny = NYdate(jula_newyear)
            dny = date(dtny.year,dtny.month,dtny.day)

            
        temp = (jula_newyear*292207)+373
        ahra = (temp//800)+1
        jultin =  temp%800

        kj = 800-jultin
        temp,aw= divmod((ahra*11)+650,692)
        masG,dT=divmod((ahra+temp),30)

        au = (ahra-621)%3232
        van = ahra%7

        stin = (d-dny).days
        sec = (dt-dtf).seconds

        ahra_ = ahra+stin
        stkm = (stin-1)*800
        kj_ = kj + stkm + sec//108

        awjt = (stin-1)*703+aw
        aws = awjt+(sec*703)//86400
        awdT,aw_=divmod(aws,692)
        temp,dT_=divmod((awdT+dT),30)
        masG_ = masG+temp
        van_=ahra_%7

        if (au+stin > 3232):
            au_ = au+stin-3232
        else: au_= au+stin        
        
        
##########################SUN###############################
        sun_table = [[35,32,27,22,13,5,0],
                     [0,35,67,94,116,129,134]]

        z = kj_ // 24350
        z_remainder = kj_ % 24350
        degree = z_remainder//811
        d_remainder = z_remainder % 811
        minute = d_remainder//14

        d_total = z*30+degree
        mathasun = d_total*60+minute-3
        
        
        if mathasun < 0:
            mathasun = mathasun+21600     
        if mathasun >= 21600:
            raise Exception('mathasun exceed or equal 21600')      
            
        if mathasun < 4800:
            pholsun = 21600+mathasun-4800
        else:
            pholsun = mathasun-4800


        if pholsun >= 21600:
            raise Exception('pholsun exceed or equal 21600')
        elif pholsun < 0:
            raise Exception('pholsun below 0')
        elif pholsun >= 0 and pholsun <5400:
            pholGA = pholsun

        elif pholsun >= 5400 and pholsun <10800:
            pholGA = 10800-pholsun

        elif pholsun >= 10800 and pholsun <16200:
            pholGA = pholsun-10800

        elif pholsun >= 16200:
            pholGA = 21600-pholsun


        khan = pholGA // 900
        pushlip = pholGA % 900


        jyaGA = (sun_table[0][khan]*pushlip) // 900
        ravipphol = sun_table[1][khan]+jyaGA


        if pholsun < 10800:
            Ssun = mathasun-ravipphol
        elif pholsun > 10800:
            Ssun= mathasun+ravipphol
        elif pholsun == 10800:
            if(ravipphol != 0):raise Exception('pholsun=10800 but ravipphol not 0')
            Ssun= mathasun

        if Ssun < 0:
            Ssun = Ssun+21600
        elif Ssun > 21600:
            Ssun= Ssun-21600

        #parameter for sun calculation
        self.mathasun = mathasun
        self.pholsun = pholsun
        self.SPholGA = pholGA
        self.SKhan = khan
        self.SPushlip = pushlip
        self.SJyaGA = jyaGA
        self.ravipphol = ravipphol               

        #zodiac,frac = divmod(Ssun,1800)
        #degree,minute = divmod(frac,60)    

#         print('pholGA =',pholGA)
#         print('khan =',khan)
#         print('kj_ =',kj_)
#         print('mathasun =',mathasun)
#         print('Ssun =',Ssun)

##########################MOON###############################

        moon_table = [[77,71,61,47,30,10,0],
                     [0,77,148,209,256,286,296]]

        temp = (au_-1)*86400+sec

        #zodiac,frac = divmod(x,23270400)
        #degree,frac = divmod(frac,775680)
        #minute = frac // 12928

        zodiac = temp//23270400
        degree = (temp%23270400)//775680
        minute = ((temp%23270400)%775680)//12928
        d_total = zodiac*30+degree
        mtu = d_total*60+minute+2


        mathamoon = mathasun + aw_ +(aw_//25)+(dT_*720)-40
        if mathamoon >= 21600: 
            mathamoon = mathamoon-21600
        if mtu >= 21600: 
            mtu = mtu-21600

#        if mathamoon >= 21600:
#            raise Exception('mathamoon exceed or equal 21600')
#        if mtu >= 21600:
#            raise Exception('mtu exceed or equal 21600')
        if mathamoon < 0:
            raise Exception('mathamoon below 0')
        elif mtu < 0:
            raise Exception('mtu below 0')
        elif mathamoon>=mtu:
            uv =  mathamoon-mtu
        elif mathamoon<mtu:
            uv = 21600+mathamoon-mtu


        if uv >= 21600:
            raise Exception('uv exceed or equal 21600')
        elif uv < 0:
            raise Exception('uv below 0')
        elif uv >= 0 and uv <5400:
            pholGA = uv
        elif uv >= 5400 and uv <10800:
            pholGA = 10800-uv
        elif uv >= 10800 and uv <16200:
            pholGA = uv-10800
        elif uv >= 16200:
            pholGA = 21600-uv


        khan = pholGA // 900
        pushlip = pholGA % 900

        jyaGA = (moon_table[0][khan]*pushlip) // 900
        chandraphol = moon_table[1][khan]+jyaGA

        if uv < 10800:
            Smoon = mathamoon-chandraphol
        elif uv > 10800:
            Smoon= mathamoon+chandraphol
        elif uv == 10800:
            if(chandraphol != 0):raise Exception('uv=10800 but chandraphol not 0')
            Smoon= mathamoon

        if Smoon < 0:
            Smoon = Smoon+21600
        elif Smoon > 21600:
            Smoon= Smoon-21600

        #parameter for moon calculation
        self.mtu = mtu
        self.mathamoon = mathamoon
        self.uv = uv
        self.MPholGA = pholGA
        self.MKhan = khan
        self.MPushlip = pushlip
        self.MJyaGA = jyaGA
        self.chandraphol = chandraphol
    
    
##########################RAHU###############################
        matharavi = mathasun-23
        srb = jula_newyear-610
        manut = (srb*21600)+ matharavi

        a = manut//20
        b = manut//265
        pmt = (a+b)%21600

        Srahu = 15150-pmt
        if Srahu<0:
            Srahu = Srahu+21600

##########################GETH###############################
        pholgt = (ahra_-345)%679
        mathageth = (pholgt*21600 + (sec*21600)//86400)//679
        Sgeth = 21600-mathageth
        zodiac,frac = divmod(Sgeth,1800)
        degree,minute = divmod(frac,60)

        


                
##########################Inner Plannets##################################
        plannet = ['mercury','venus']
        for plannet in plannet: 
            if plannet  == 'mercury':
                matha = ((manut*7)//46 + (manut*4)//1 + 10642)%21600
                pholPK = matharavi-13200
            elif plannet == 'venus':
                matha = ((manut*5)//3 - (manut*10)//243 + 10944)%21600
                pholPK = matharavi-4800
                
            if pholPK<0:
                pholPK = pholPK+21600

            ptma = (pholPK//5400)+1
            if ptma == 1:
                puchaPT = pholPK
                khotiPT = 5400-pholPK
            elif ptma == 2:
                puchaPT = 10800-pholPK
                khotiPT = pholPK-5400
            elif ptma == 3:
                puchaPT = pholPK-10800
                khotiPT = 16200-pholPK
            elif ptma == 4:
                puchaPT = 21600-pholPK
                khotiPT = pholPK-16200

            # puchaPT = 1064
            # khotiPT = 4336

            if puchaPT < 0:
                raise Exception('puchaPT is below 0')
            elif puchaPT > 5400:
                raise Exception('puchaPT is greater than 5400')
            elif puchaPT < 1800:
                MTpucha = (puchaPT*14640)//1800
            elif (puchaPT >= 1800) and (puchaPT < 3600) :
                MTpucha = (((puchaPT-1800)*10980)//1800)+14640
            elif puchaPT >= 3600 :
                MTpucha = (((puchaPT-3600)*3660)//1800)+25620

            if khotiPT < 0:
                raise Exception('khotiPT is below 0')
            elif khotiPT > 5400:
                raise Exception('khotiPT is greater than 5400')
            elif khotiPT < 1800:
                MTKhoti = (khotiPT*14640)//1800
            elif (khotiPT >= 1800) and (khotiPT < 3600) :
                MTKhoti = (((khotiPT-1800)*10980)//1800)+14640
            elif khotiPT >= 3600 :
                MTKhoti = (((khotiPT-3600)*3660)//1800)+25620

            MTKhoti = (MTKhoti+30)//60
            khotiphol = MTKhoti//2


            if plannet == 'mercury':
                if (ptma ==1) or (ptma ==4):
                    MTcheta = 100*60 + khotiphol
                elif (ptma ==2) or (ptma ==3):
                    MTcheta=  100*60 - khotiphol
            elif plannet == 'venus':
                if (ptma ==1) or (ptma ==4):
                    MTcheta = 320*60 + khotiphol
                elif (ptma ==2) or (ptma ==3):
                    MTcheta=  320*60 - khotiphol          
            
            

            MTphol = (MTpucha*60)//MTcheta


            if (ptma ==1) or (ptma ==2):
                if (matharavi  - MTphol)>=0:
                    MTS = matharavi  - MTphol
                elif (matharavi  - MTphol)<0:
                    MTS =  matharavi  - MTphol + 21600
                    print('MTS =',matharavi  - MTphol,'adjust to',MTS)          

            elif (ptma ==3) or (ptma ==4):
                if (matharavi  + MTphol)>=21600:
                    MTS = matharavi  + MTphol - 21600
                    print('MTS =',matharavi  + MTphol,'adjust to',MTS)
                elif(matharavi  + MTphol)<21600:
                    MTS = matharavi  + MTphol


            pholMT = MTS-matha
            if pholMT<0:
                pholMT=pholMT+21600

            ptnd = (pholMT//5400)+1
            if ptnd == 1:
                puchaTY = pholMT
                khotiTY = 5400-pholMT
            elif ptnd == 2:
                puchaTY = 10800-pholMT
                khotiTY = pholMT-5400
            elif ptnd == 3:
                puchaTY = pholMT-10800
                khotiTY = 16200-pholMT
            elif ptnd == 4:
                puchaTY = 21600-pholMT
                khotiTY = pholMT-16200

            if puchaTY < 0:
                raise Exception('puchaTY is below 0')
            elif puchaTY > 5400:
                raise Exception('puchaTY is greater than 5400')
            elif puchaTY < 1800:
                SGPucha = (puchaTY*14640)//1800
            elif (puchaTY >= 1800) and (puchaTY < 3600) :
                SGPucha = (((puchaTY-1800)*10980)//1800)+14640
            elif puchaTY >= 3600 :
                SGPucha = (((puchaTY-3600)*3660)//1800)+25620

            if khotiTY < 0:
                raise Exception('khotiTY is below 0')
            elif khotiTY > 5400:
                raise Exception('khotiTY is greater than 5400')
            elif khotiTY < 1800:
                SGKhoti = (khotiTY*14640)//1800
            elif (khotiTY >= 1800) and (khotiTY < 3600) :
                SGKhoti = (((khotiTY-1800)*10980)//1800)+14640
            elif khotiTY >= 3600 :
                SGKhoti = (((khotiTY-3600)*3660)//1800)+25620

            SGKhoti = (SGKhoti+30)//60
            SGphol = ((SGPucha+30)//60)//3


            if plannet == 'mercury': p= 21*60
            elif plannet == 'venus': p= 11*60            
            
            
            sp = p+SGphol

            if (ptnd ==1) or (ptnd ==4):
                SGcheta = sp + SGKhoti
            elif (ptnd ==2) or (ptnd ==3):
                SGcheta = sp - SGKhoti

            if SGcheta < 0:
                raise Exception('SGcheta < 0')
            elif khotiTY > 21600:
                raise Exception('SGcheta > SGcheta')

            mahaphol = (SGPucha*60)//SGcheta
            
            
            
            if plannet == 'mercury': 
                if (ptnd ==1) or (ptnd ==2):
                    if (MTS - mahaphol)>=0:
                        SMercury = MTS - mahaphol
                    elif (MTS - mahaphol)<0:
                        SMercury =  MTS - mahaphol + 21600
                        print('Smercury =',MTS - mahaphol,'adjust to',SMercury)          

                elif (ptnd ==3) or (ptnd ==4):
                    if (MTS + mahaphol)>=21600:
                        SMercury = MTS + mahaphol - 21600
                        print('SMercury =',MTS + mahaphol,'adjust to',SMercury)
                    elif(MTS + mahaphol)<21600:
                        SMercury = MTS + mahaphol
            elif plannet == 'venus': 
                if (ptnd ==1) or (ptnd ==2):
                    if (MTS - mahaphol)>=0:
                        SVenus = MTS - mahaphol
                    elif (MTS - mahaphol)<0:
                        SVenus =  MTS - mahaphol + 21600
                        print('SVenus =',MTS - mahaphol,'adjust to',SVenus)          

                elif (ptnd ==3) or (ptnd ==4):
                    if (MTS + mahaphol)>=21600:
                        SVenus = MTS + mahaphol - 21600
                        print('SVenus =',MTS + mahaphol,'adjust to',SVenus)
                    elif(MTS + mahaphol)<21600:
                        SVenus = MTS + mahaphol               





                
##########################Other Plannets####################################

        plannet = ['mars','jupiter','saturn','uranus']
        for plannet in plannet: 
 
            if plannet  == 'mars':
                matha  =  ((manut*1)//2 + (manut*16)//505 + 5420)%21600         
                pholPK = matha-7620
            elif plannet == 'jupiter':
                matha  = ((manut*1)//12 + (manut*1)//1032 + 14297)%21600
                pholPK = matha-10320
            elif plannet == 'saturn':
                matha  = ((manut*1)//30 + (manut*6)//10000 + 11944)%21600
                pholPK = matha-14820
            elif plannet == 'uranus':
                matha  = ((manut*1)//84 + (manut*1)//7224 + 16277)%21600
                pholPK = matha-7440        

            if pholPK<0:
                pholPK = pholPK+21600


            ptma = (pholPK//5400)+1
            if ptma == 1:
                puchaPT = pholPK
                khotiPT = 5400-pholPK
            elif ptma == 2:
                puchaPT = 10800-pholPK
                khotiPT = pholPK-5400
            elif ptma == 3:
                puchaPT = pholPK-10800
                khotiPT = 16200-pholPK
            elif ptma == 4:
                puchaPT = 21600-pholPK
                khotiPT = pholPK-16200

            # puchaPT = 1064
            # khotiPT = 4336

            if puchaPT < 0:
                raise Exception('puchaPT is below 0')
            elif puchaPT > 5400:
                raise Exception('puchaPT is greater than 5400')
            elif puchaPT < 1800:
                MTpucha = (puchaPT*14640)//1800
            elif (puchaPT >= 1800) and (puchaPT < 3600) :
                MTpucha = (((puchaPT-1800)*10980)//1800)+14640
            elif puchaPT >= 3600 :
                MTpucha = (((puchaPT-3600)*3660)//1800)+25620

            if khotiPT < 0:
                raise Exception('khotiPT is below 0')
            elif khotiPT > 5400:
                raise Exception('khotiPT is greater than 5400')
            elif khotiPT < 1800:
                MTKhoti = (khotiPT*14640)//1800
            elif (khotiPT >= 1800) and (khotiPT < 3600) :
                MTKhoti = (((khotiPT-1800)*10980)//1800)+14640
            elif khotiPT >= 3600 :
                MTKhoti = (((khotiPT-3600)*3660)//1800)+25620

            MTKhoti = (MTKhoti+30)//60
            khotiphol = MTKhoti//2


            if plannet == 'mars':
                if (ptma ==1) or (ptma ==4):
                    MTcheta = 45*60 + khotiphol
                elif (ptma ==2) or (ptma ==3):
                    MTcheta=  45*60 - khotiphol
            elif plannet == 'jupiter':
                if (ptma ==1) or (ptma ==4):
                    MTcheta = 92*60 + khotiphol
                elif (ptma ==2) or (ptma ==3):
                    MTcheta=  92*60 - khotiphol
            elif plannet == 'saturn':
                if (ptma ==1) or (ptma ==4):
                    MTcheta = 63*60 + khotiphol
                elif (ptma ==2) or (ptma ==3):
                    MTcheta=  63*60 - khotiphol
            elif plannet == 'uranus':
                if (ptma ==1) or (ptma ==4):
                    MTcheta = 644*60 + khotiphol
                elif (ptma ==2) or (ptma ==3):
                    MTcheta=  644*60 - khotiphol  



            MTphol = (MTpucha*60)//MTcheta


            if (ptma ==1) or (ptma ==2):
                if (matha - MTphol)>=0:
                    MTS = matha - MTphol
                elif (matha - MTphol)<0:
                    MTS =  matha - MTphol + 21600
                    print('MTS =',matha - MTphol,'adjust to',MTS)          

            elif (ptma ==3) or (ptma ==4):
                if (matha + MTphol)>=21600:
                    MTS = matha + MTphol - 21600
                    print('MTS =',matha + MTphol,'adjust to',MTS)
                elif(matha + MTphol)<21600:
                    MTS = matha + MTphol


            pholMT = MTS-matharavi
            if pholMT<0:
                pholMT=pholMT+21600

            ptnd = (pholMT//5400)+1
            if ptnd == 1:
                puchaTY = pholMT
                khotiTY = 5400-pholMT
            elif ptnd == 2:
                puchaTY = 10800-pholMT
                khotiTY = pholMT-5400
            elif ptnd == 3:
                puchaTY = pholMT-10800
                khotiTY = 16200-pholMT
            elif ptnd == 4:
                puchaTY = 21600-pholMT
                khotiTY = pholMT-16200

            if puchaTY < 0:
                raise Exception('puchaTY is below 0')
            elif puchaTY > 5400:
                raise Exception('puchaTY is greater than 5400')
            elif puchaTY < 1800:
                SGPucha = (puchaTY*14640)//1800
            elif (puchaTY >= 1800) and (puchaTY < 3600) :
                SGPucha = (((puchaTY-1800)*10980)//1800)+14640
            elif puchaTY >= 3600 :
                SGPucha = (((puchaTY-3600)*3660)//1800)+25620

            if khotiTY < 0:
                raise Exception('khotiTY is below 0')
            elif khotiTY > 5400:
                raise Exception('khotiTY is greater than 5400')
            elif khotiTY < 1800:
                SGKhoti = (khotiTY*14640)//1800
            elif (khotiTY >= 1800) and (khotiTY < 3600) :
                SGKhoti = (((khotiTY-1800)*10980)//1800)+14640
            elif khotiTY >= 3600 :
                SGKhoti = (((khotiTY-3600)*3660)//1800)+25620

            SGKhoti = (SGKhoti+30)//60
            SGphol = ((SGPucha+30)//60)//3

            
            if plannet == 'mars': p= (4*MTcheta)//15 
            elif plannet == 'jupiter': p= (3*MTcheta)//7
            elif plannet == 'saturn': p= (7*MTcheta)//6 
            elif plannet == 'uranus':p= (3*MTcheta)//7 
    

            sp = p+SGphol
            if (ptnd ==1) or (ptnd ==4):
                SGcheta = sp + SGKhoti
            elif (ptnd ==2) or (ptnd ==3):
                SGcheta = sp - SGKhoti

            if SGcheta < 0:
                raise Exception('SGcheta < 0')
            elif khotiTY > 21600:
                raise Exception('SGcheta > SGcheta')

            mahaphol = (SGPucha*60)//SGcheta

            

            if plannet == 'mars':
                if (ptnd ==1) or (ptnd ==2):
                    if (MTS - mahaphol)>=0:
                        Smars = MTS - mahaphol
                    elif (MTS - mahaphol)<0:
                        Smars =  MTS - mahaphol + 21600
                        print('Smars =',MTS - mahaphol,'adjust to',Smars)          

                elif (ptnd ==3) or (ptnd ==4):
                    if (MTS + mahaphol)>=21600:
                        Smars = MTS + mahaphol - 21600
                        print('Smars =',MTS + mahaphol,'adjust to',Smars)
                    elif(MTS + mahaphol)<21600:
                        Smars = MTS + mahaphol 
            elif plannet == 'jupiter':
                if (ptnd ==1) or (ptnd ==2):
                    if (MTS - mahaphol)>=0:
                        Jupiter = MTS - mahaphol
                    elif (MTS - mahaphol)<0:
                        Jupiter =  MTS - mahaphol + 21600
                        print('Jupiter =',MTS - mahaphol,'adjust to',Jupiter)          

                elif (ptnd ==3) or (ptnd ==4):
                    if (MTS + mahaphol)>=21600:
                        Jupiter = MTS + mahaphol - 21600
                        print('Jupiter =',MTS + mahaphol,'adjust to',Jupiter)
                    elif(MTS + mahaphol)<21600:
                        Jupiter = MTS + mahaphol 
            elif plannet == 'saturn':
                if (ptnd ==1) or (ptnd ==2):
                    if (MTS - mahaphol)>=0:
                        SSaturn = MTS - mahaphol
                    elif (MTS - mahaphol)<0:
                        SSaturn =  MTS - mahaphol + 21600
                        print('SSaturn =',MTS - mahaphol,'adjust to',SSaturn)          

                elif (ptnd ==3) or (ptnd ==4):
                    if (MTS + mahaphol)>=21600:
                        SSaturn = MTS + mahaphol - 21600
                        print('SSaturn =',MTS + mahaphol,'adjust to',SSaturn)
                    elif(MTS + mahaphol)<21600:
                        SSaturn = MTS + mahaphol
            elif plannet == 'uranus':
                if (ptnd ==1) or (ptnd ==2):
                    if (MTS - mahaphol)>=0:
                        SUranus = MTS - mahaphol
                    elif (MTS - mahaphol)<0:
                        SUranus =  MTS - mahaphol + 21600
                        print('SUranus =',MTS - mahaphol,'adjust to',SUranus)          

                elif (ptnd ==3) or (ptnd ==4):
                    if (MTS + mahaphol)>=21600:
                        SUranus = MTS + mahaphol - 21600
                        print('SUranus =',MTS + mahaphol,'adjust to',SUranus)
                    elif(MTS + mahaphol)<21600:
                        SUranus = MTS + mahaphol 
    



        

#         print('uv =',uv)
#         print('pholGA =',pholGA)
#         print('khan =',khan)
#         print('Smoon =',Smoon)

#         print('au_ =',au_)
#         print('mtu =',mtu)
#         print('uv =',uv)
#         print('Smoon =',Smoon)

        #TS Parameter (yearly parameter) 
        self.dt = dt  
        self.dtny = dtny 
        self.dny = dny 
        self.ahra = ahra 
        self.jultin = jultin 
        self.kj = kj 
        self.aw = aw 
        self.masG = masG 
        self.dT = dT
        self.au = au 
        self.van = van 
        
        #Given Datetime parameter
        self.stin = stin 
        self.sec = sec 
        self.ahra_ = ahra_ 
        self.kj_ = kj_ 
        self.aw_ = aw_ 
        self.masG_ = masG_ 
        self.dT_ = dT_
        self.au_ = au_ 
        self.van_ = van_
    
        
        ##locations in zodiac (minutes maximum = 21600)         
        self.sun = Ssun
        self.moon = Smoon
        self.rahu = Srahu
        self.geth = Sgeth
        self.mars = Smars
        self.mercury = SMercury
        self.venus = SVenus
        self.jupiter = Jupiter
        self.saturn = SSaturn
        self.uranus = SUranus

In [7]:
startdate = datetime(2039,4,16,22,0)
df = pd.DataFrame()
#count = 108000
count = 1000
#count = 1000

#select timeframe
#interval = 'day'
interval = 'minutes'

for i in range(0,count):
    if interval=='minutes':
        diff = timedelta(minutes=i)
    elif interval=='day':
        diff = timedelta(days=i)
        
    dt = startdate+diff
    h = hora(dt)    
    data = {
        #'dt': dt,
        #'dtny': h.dtny,        
        'dt': str(dt.day)+'/'+str(dt.month)+'/'+str(dt.year+543)+' '+str(dt.hour)+':'+str(dt.minute),
        'dtny': str(h.dtny.day)+'/'+str(h.dtny.month)+'/'+str(h.dtny.year+543)+' '+str(h.dtny.hour)+':'+str(h.dtny.minute)+':'+str(h.dtny.second),
        
        #TS parameter
        'ahra' : h.ahra, 'jultin': h.jultin, 'kj' : h.kj, 'aw' : h.aw, 'masG' : h.masG, 'dT' : h.dT, 'au' : h.au, 'van' : h.van,
        
        #GivenDT parameter
        'stin' : h.stin, 'sec': h.sec, 'ahra_' : h.ahra_, 'kj_' : h.kj_, 'aw_' : h.aw_, 'masG_' : h.masG_, 'dT_' : h.dT_, 'au_' : h.au_, 'van_' : h.van_,
        
        #parameter for sun and moon calculation  
        #Sun
        'mathasun' : h.mathasun, 'pholsun': h.pholsun, 'SPholGA' : h.SPholGA, 'SKhan': h.SKhan, 'SPushlip' : h.SPushlip,'SJyaGA' : h.SJyaGA, 'ravipphol': h.ravipphol,        
        #Moon
        'mtu' : h.mtu, 'mathamoon': h.mathamoon, 'uv' : h.uv, 'MPholGA' : h.MPholGA, 'MKhan': h.MKhan, 'MPushlip' : h.MPushlip,'MJyaGA' : h.MJyaGA, 'chandraphol': h.chandraphol,

        #Constellation 
        'sun' : h.sun, 'moon': h.moon, 'rahu' : h.rahu, 'geth' : h.geth, 'mars' : h.mars, 'mercury' : h.mercury, 'venus' : h.venus, 'jupiter' : h.jupiter, 'saturn' : h.saturn, 'uranus' : h.uranus
              
    }


    print(dt.day,dt.month,dt.year,dt.hour,':',dt.minute)
    #df = pd.DataFrame(data)
    df = df.append(data , ignore_index=True)


ListofPlannets = ['sun','moon','rahu','geth','mars','mercury','venus','jupiter','saturn','uranus'] 
for planet in ListofPlannets:
    zodiac = planet+"_Z"
    degree = planet+"_D"
    minute = planet+"_M"
    df[zodiac] =  df[planet]//1800 
    df[degree] =  (df[planet]%1800)//60 
    df[minute] =  (df[planet]%1800)%60
    
#df['sun_delta'] = df['sun'] 


#df.to_csv(r"C:\Users\JACK\Desktop\S_out.csv")

#df.dtypes

# data = {
#     'dt': [startdate],
#     'sun' : [h.sun],
#     'moon': [h.moon],
#     'rahu' : [h.rahu],
#     'geth' : [h.geth],
#     'mars' : [h.mars],
#     'mercury' : [h.mercury],
#     'venus' : [h.venus],
#     'jupiter' : [h.jupiter],
#     'saturn' : [h.saturn],
#     'uranus' : [h.uranus]
# }
#startdate = datetime(2019,4,16,0,0) mathasun-

MTS = 21656 adjust to 56
16 4 2039 22 : 0
MTS = 21656 adjust to 56
16 4 2039 22 : 1
MTS = 21656 adjust to 56
16 4 2039 22 : 2
MTS = 21656 adjust to 56
16 4 2039 22 : 3
MTS = 21656 adjust to 56
16 4 2039 22 : 4
MTS = 21657 adjust to 57
16 4 2039 22 : 5
MTS = 21657 adjust to 57
16 4 2039 22 : 6
MTS = 21657 adjust to 57
16 4 2039 22 : 7
MTS = 21657 adjust to 57
16 4 2039 22 : 8
MTS = 21657 adjust to 57
16 4 2039 22 : 9
MTS = 21657 adjust to 57
16 4 2039 22 : 10
MTS = 21657 adjust to 57
16 4 2039 22 : 11
MTS = 21657 adjust to 57
16 4 2039 22 : 12
MTS = 21657 adjust to 57
16 4 2039 22 : 13
MTS = 21657 adjust to 57
16 4 2039 22 : 14
MTS = 21657 adjust to 57
16 4 2039 22 : 15
MTS = 21657 adjust to 57
16 4 2039 22 : 16
MTS = 21657 adjust to 57
16 4 2039 22 : 17
MTS = 21657 adjust to 57
16 4 2039 22 : 18
MTS = 21657 adjust to 57
16 4 2039 22 : 19
MTS = 21657 adjust to 57
16 4 2039 22 : 20
MTS = 21657 adjust to 57
16 4 2039 22 : 21
MTS = 21657 adjust to 57
16 4 2039 22 : 22
MTS = 21657 adjust to 57
16 4 2039 22 : 23
MTS = 21657 adjust to 57
16 4 2039 22 : 24
MTS = 21657 adjust to 57
16 4 2039 22 : 25
MTS = 21657 adjust to 57
16 4 2039 22 : 26
MTS = 21657 adjust to 57
16 4 2039 22 : 27
MTS = 21657 adjust to 57
16 4 2039 22 : 28
MTS = 21657 adjust to 57
16 4 2039 22 : 29
MTS = 21658 adjust to 58
16 4 2039 22 : 30
MTS = 21658 adjust to 58
16 4 2039 22 : 31
MTS = 21658 adjust to 58
16 4 2039 22 : 32
MTS = 21658 adjust to 58
16 4 2039 22 : 33
MTS = 21658 adjust to 58
16 4 2039 22 : 34
MTS = 21658 adjust to 58
16 4 2039 22 : 35
MTS = 21658 adjust to 58
16 4 2039 22 : 36
MTS = 21658 adjust to 58
16 4 2039 22 : 37
MTS = 21658 adjust to 58
16 4 2039 22 : 38
MTS = 21658 adjust to 58
16 4 2039 22 : 39
MTS = 21658 adjust to 58
16 4 2039 22 : 40
MTS = 21658 adjust to 58
16 4 2039 22 : 41
MTS = 21658 adjust to 58
16 4 2039 22 : 42
MTS = 21658 adjust to 58
16 4 2039 22 : 43
MTS = 21658 adjust to 58
16 4 2039 22 : 44
MTS = 21658 adjust to 58
16 4 2039 22 : 45
MTS = 21658 adjust to 58
16 4 2039 22 : 46
MTS = 21658 adjust to 58
16 4 2039 22 : 47
MTS = 21658 adjust to 58
16 4 2039 22 : 48
MTS = 21658 adjust to 58
16 4 2039 22 : 49
MTS = 21658 adjust to 58
16 4 2039 22 : 50
MTS = 21658 adjust to 58
16 4 2039 22 : 51
MTS = 21658 adjust to 58
16 4 2039 22 : 52
MTS = 21658 adjust to 58
16 4 2039 22 : 53
MTS = 21661 adjust to 61
16 4 2039 22 : 54
MTS = 21661 adjust to 61
16 4 2039 22 : 55
MTS = 21661 adjust to 61
16 4 2039 22 : 56
MTS = 21661 adjust to 61
16 4 2039 22 : 57
MTS = 21661 adjust to 61
16 4 2039 22 : 58
MTS = 21661 adjust to 61
16 4 2039 22 : 59
MTS = 21661 adjust to 61
16 4 2039 23 : 0
MTS = 21661 adjust to 61
16 4 2039 23 : 1
MTS = 21661 adjust to 61
16 4 2039 23 : 2
MTS = 21661 adjust to 61
16 4 2039 23 : 3
MTS = 21661 adjust to 61
16 4 2039 23 : 4
MTS = 21661 adjust to 61
16 4 2039 23 : 5
MTS = 21661 adjust to 61
16 4 2039 23 : 6
MTS = 21661 adjust to 61
16 4 2039 23 : 7
MTS = 21661 adjust to 61
16 4 2039 23 : 8
MTS = 21661 adjust to 61
16 4 2039 23 : 9
MTS = 21661 adjust to 61
16 4 2039 23 : 10
MTS = 21661 adjust to 61
16 4 2039 23 : 11
MTS = 21661 adjust to 61
16 4 2039 23 : 12
MTS = 21661 adjust to 61
16 4 2039 23 : 13
MTS = 21661 adjust to 61
16 4 2039 23 : 14
MTS = 21661 adjust to 61
16 4 2039 23 : 15
MTS = 21661 adjust to 61
16 4 2039 23 : 16
MTS = 21661 adjust to 61
16 4 2039 23 : 17
MTS = 21661 adjust to 61
16 4 2039 23 : 18
MTS = 21662 adjust to 62
16 4 2039 23 : 19
MTS = 21662 adjust to 62
16 4 2039 23 : 20
MTS = 21662 adjust to 62
16 4 2039 23 : 21
MTS = 21662 adjust to 62
16 4 2039 23 : 22
MTS = 21662 adjust to 62
16 4 2039 23 : 23
MTS = 21662 adjust to 62
16 4 2039 23 : 24
MTS = 21662 adjust to 62
16 4 2039 23 : 25
MTS = 21662 adjust to 62
16 4 2039 23 : 26
MTS = 21662 adjust to 62
16 4 2039 23 : 27
MTS = 21662 adjust to 62
16 4 2039 23 : 28
MTS = 21662 adjust to 62
16 4 2039 23 : 29
MTS = 21661 adjust to 61
16 4 2039 23 : 30
MTS = 21661 adjust to 61
16 4 2039 23 : 31
MTS = 21661 adjust to 61
16 4 2039 23 : 32
MTS = 21661 adjust to 61
16 4 2039 23 : 33
MTS = 21661 adjust to 61
16 4 2039 23 : 34
MTS = 21661 adjust to 61
16 4 2039 23 : 35
MTS = 21661 adjust to 61
16 4 2039 23 : 36
MTS = 21661 adjust to 61
16 4 2039 23 : 37
MTS = 21661 adjust to 61
16 4 2039 23 : 38
MTS = 21661 adjust to 61
16 4 2039 23 : 39
MTS = 21661 adjust to 61
16 4 2039 23 : 40
MTS = 21661 adjust to 61
16 4 2039 23 : 41
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 42
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 43
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 44
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 45
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 46
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 47
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 48
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 49
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 50
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 51
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 52
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 53
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 54
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 55
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 56
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 57
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 58
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
16 4 2039 23 : 59
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
17 4 2039 0 : 0
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
17 4 2039 0 : 1
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
17 4 2039 0 : 2
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
17 4 2039 0 : 3
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
17 4 2039 0 : 4
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
17 4 2039 0 : 5
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
17 4 2039 0 : 6
MTS = 21661 adjust to 61
SVenus = -748 adjust to 20852
17 4 2039 0 : 7
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 8
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 9
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 10
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 11
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 12
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 13
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 14
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 15
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 16
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 17
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 18
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 19
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 20
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 21
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 22
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 23
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 24
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 25
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 26
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 27
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 28
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 29
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 30
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 31
MTS = 21662 adjust to 62
SVenus = -747 adjust to 20853
17 4 2039 0 : 32
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 33
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 34
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 35
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 36
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 37
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 38
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 39
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 40
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 41
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 42
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 43
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 44
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 45
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 46
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 47
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 48
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 49
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 50

MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 51
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 52
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 53
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 54
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 55
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 56
MTS = 21663 adjust to 63
SVenus = -746 adjust to 20854
17 4 2039 0 : 57
MTS = -213 adjust to 21387
17 4 2039 0 : 58
MTS = -213 adjust to 21387
17 4 2039 0 : 59
MTS = -213 adjust to 21387
17 4 2039 1 : 0
MTS = -213 adjust to 21387
17 4 2039 1 : 1
MTS = -213 adjust to 21387
17 4 2039 1 : 2
MTS = -213 adjust to 21387
17 4 2039 1 : 3
MTS = -213 adjust to 21387
17 4 2039 1 : 4
MTS = -213 adjust to 21387
17 4 2039 1 : 5
MTS = -213 adjust to 21387
17 4 2039 1 : 6
MTS = -213 adjust to 21387
17 4 2039 1 : 7
MTS = -213 adjust to 21387
17 4 2039 1 : 8
MTS = -213 adjust to 21387
17 4 2039 1 : 9
MTS = -213 adjust to 21387
17 4 2039 1 : 10
MTS = -213 adjust to 21387
17 4 2039 1 : 11
MTS = -213 adjust to 21387
17 4 2039 1 : 12
MTS = -213 adjust to 21387
17 4 2039 1 : 13
MTS = -213 adjust to 21387
17 4 2039 1 : 14
MTS = -213 adjust to 21387
17 4 2039 1 : 15
MTS = -213 adjust to 21387
17 4 2039 1 : 16
MTS = -213 adjust to 21387
17 4 2039 1 : 17
MTS = -213 adjust to 21387
17 4 2039 1 : 18
MTS = -213 adjust to 21387
17 4 2039 1 : 19
MTS = -213 adjust to 21387
17 4 2039 1 : 20
MTS = -213 adjust to 21387
17 4 2039 1 : 21
MTS = -213 adjust to 21387
17 4 2039 1 : 22
MTS = -212 adjust to 21388
17 4 2039 1 : 23
MTS = -212 adjust to 21388
17 4 2039 1 : 24
MTS = -212 adjust to 21388
17 4 2039 1 : 25
MTS = -212 adjust to 21388
17 4 2039 1 : 26
MTS = -212 adjust to 21388
17 4 2039 1 : 27
MTS = -212 adjust to 21388
17 4 2039 1 : 28
MTS = -212 adjust to 21388
17 4 2039 1 : 29
MTS = -212 adjust to 21388
17 4 2039 1 : 30
MTS = -212 adjust to 21388
17 4 2039 1 : 31
MTS = -212 adjust to 21388
17 4 2039 1 : 32
MTS = -212 adjust to 21388
17 4 2039 1 : 33
MTS = -212 adjust to 21388
17 4 2039 1 : 34
MTS = -212 adjust to 21388
17 4 2039 1 : 35
MTS = -212 adjust to 21388
17 4 2039 1 : 36
MTS = -212 adjust to 21388
17 4 2039 1 : 37
MTS = -212 adjust to 21388
17 4 2039 1 : 38
MTS = -212 adjust to 21388
17 4 2039 1 : 39
MTS = -212 adjust to 21388
17 4 2039 1 : 40
MTS = -212 adjust to 21388
17 4 2039 1 : 41
MTS = -212 adjust to 21388
17 4 2039 1 : 42
MTS = -212 adjust to 21388
17 4 2039 1 : 43
MTS = -212 adjust to 21388
17 4 2039 1 : 44
MTS = -212 adjust to 21388
17 4 2039 1 : 45
MTS = -212 adjust to 21388
17 4 2039 1 : 46
MTS = -212 adjust to 21388
17 4 2039 1 : 47
MTS = -211 adjust to 21389
17 4 2039 1 : 48
MTS = -211 adjust to 21389
17 4 2039 1 : 49
MTS = -211 adjust to 21389
17 4 2039 1 : 50
MTS = -211 adjust to 21389
17 4 2039 1 : 51
MTS = -211 adjust to 21389
17 4 2039 1 : 52
MTS = -211 adjust to 21389
17 4 2039 1 : 53
MTS = -211 adjust to 21389
17 4 2039 1 : 54
MTS = -211 adjust to 21389
17 4 2039 1 : 55
MTS = -211 adjust to 21389
17 4 2039 1 : 56
MTS = -211 adjust to 21389
17 4 2039 1 : 57
MTS = -211 adjust to 21389
17 4 2039 1 : 58
MTS = -211 adjust to 21389
17 4 2039 1 : 59
MTS = -211 adjust to 21389
17 4 2039 2 : 0
MTS = -211 adjust to 21389
17 4 2039 2 : 1
MTS = -211 adjust to 21389
17 4 2039 2 : 2
MTS = -211 adjust to 21389
17 4 2039 2 : 3
MTS = -211 adjust to 21389
17 4 2039 2 : 4
MTS = -211 adjust to 21389
17 4 2039 2 : 5
MTS = -211 adjust to 21389
17 4 2039 2 : 6
MTS = -211 adjust to 21389
17 4 2039 2 : 7
MTS = -211 adjust to 21389
17 4 2039 2 : 8
MTS = -211 adjust to 21389
17 4 2039 2 : 9
MTS = -211 adjust to 21389
17 4 2039 2 : 10
MTS = -211 adjust to 21389
17 4 2039 2 : 11
MTS = -211 adjust to 21389
17 4 2039 2 : 12
MTS = -211 adjust to 21389
17 4 2039 2 : 13
MTS = -209 adjust to 21391
17 4 2039 2 : 14
MTS = -209 adjust to 21391
17 4 2039 2 : 15
MTS = -209 adjust to 21391
17 4 2039 2 : 16
MTS = -209 adjust to 21391
17 4 2039 2 : 17
MTS = -209 adjust to 21391
17 4 2039 2 : 18
MTS = -209 adjust to 21391
17 4 2039 2 : 19
MTS = -209 adjust to 21391
17 4 2039 2 : 20
MTS = -209 adjust to 21391
17 4 2039 2 : 21
MTS = -209 adjust to 21391
17 4 2039 2 : 22
MTS = -209 adjust to 21391
17 4 2039 2 : 23
MTS = -209 adjust to 21391
17 4 2039 2 : 24
MTS = -209 adjust to 21391
17 4 2039 2 : 25
MTS = -209 adjust to 21391
17 4 2039 2 : 26
MTS = -209 adjust to 21391
17 4 2039 2 : 27
MTS = -209 adjust to 21391
17 4 2039 2 : 28
MTS = -209 adjust to 21391
17 4 2039 2 : 29
MTS = -209 adjust to 21391
17 4 2039 2 : 30
MTS = -209 adjust to 21391
17 4 2039 2 : 31
MTS = -209 adjust to 21391
17 4 2039 2 : 32
MTS = -209 adjust to 21391
17 4 2039 2 : 33
MTS = -209 adjust to 21391
17 4 2039 2 : 34
MTS = -209 adjust to 21391
17 4 2039 2 : 35
MTS = -209 adjust to 21391
17 4 2039 2 : 36
MTS = -209 adjust to 21391
17 4 2039 2 : 37
MTS = -209 adjust to 21391
17 4 2039 2 : 38
MTS = -208 adjust to 21392
17 4 2039 2 : 39
MTS = -208 adjust to 21392
17 4 2039 2 : 40
MTS = -208 adjust to 21392
17 4 2039 2 : 41
MTS = -208 adjust to 21392
17 4 2039 2 : 42
MTS = -208 adjust to 21392
17 4 2039 2 : 43
MTS = -208 adjust to 21392
17 4 2039 2 : 44
MTS = -208 adjust to 21392
17 4 2039 2 : 45
MTS = -208 adjust to 21392
17 4 2039 2 : 46
MTS = -208 adjust to 21392
17 4 2039 2 : 47
MTS = -208 adjust to 21392
17 4 2039 2 : 48
MTS = -208 adjust to 21392
17 4 2039 2 : 49
MTS = -208 adjust to 21392
17 4 2039 2 : 50
MTS = -208 adjust to 21392
17 4 2039 2 : 51
MTS = -208 adjust to 21392
17 4 2039 2 : 52
MTS = -208 adjust to 21392
17 4 2039 2 : 53
MTS = -208 adjust to 21392
17 4 2039 2 : 54
MTS = -208 adjust to 21392
17 4 2039 2 : 55
MTS = -208 adjust to 21392
17 4 2039 2 : 56
MTS = -208 adjust to 21392
17 4 2039 2 : 57
MTS = -208 adjust to 21392
17 4 2039 2 : 58
MTS = -208 adjust to 21392
17 4 2039 2 : 59
MTS = -208 adjust to 21392
17 4 2039 3 : 0
MTS = -208 adjust to 21392
17 4 2039 3 : 1
MTS = -208 adjust to 21392
17 4 2039 3 : 2
MTS = -208 adjust to 21392
17 4 2039 3 : 3
MTS = -207 adjust to 21393
17 4 2039 3 : 4
MTS = -207 adjust to 21393
17 4 2039 3 : 5
MTS = -207 adjust to 21393
17 4 2039 3 : 6
MTS = -207 adjust to 21393
17 4 2039 3 : 7
MTS = -207 adjust to 21393
17 4 2039 3 : 8
MTS = -207 adjust to 21393
17 4 2039 3 : 9
MTS = -207 adjust to 21393
17 4 2039 3 : 10
MTS = -207 adjust to 21393
17 4 2039 3 : 11
MTS = -207 adjust to 21393
17 4 2039 3 : 12
MTS = -207 adjust to 21393
17 4 2039 3 : 13
MTS = -207 adjust to 21393
17 4 2039 3 : 14
MTS = -207 adjust to 21393
17 4 2039 3 : 15
MTS = -207 adjust to 21393
17 4 2039 3 : 16
MTS = -207 adjust to 21393
17 4 2039 3 : 17
MTS = -207 adjust to 21393
17 4 2039 3 : 18
MTS = -207 adjust to 21393
17 4 2039 3 : 19
MTS = -207 adjust to 21393
17 4 2039 3 : 20
MTS = -207 adjust to 21393
17 4 2039 3 : 21
MTS = -207 adjust to 21393
17 4 2039 3 : 22
MTS = -207 adjust to 21393
17 4 2039 3 : 23
MTS = -207 adjust to 21393
17 4 2039 3 : 24
MTS = -207 adjust to 21393
17 4 2039 3 : 25
MTS = -207 adjust to 21393
17 4 2039 3 : 26
MTS = -207 adjust to 21393
17 4 2039 3 : 27
MTS = -207 adjust to 21393
17 4 2039 3 : 28
MTS = -206 adjust to 21394
17 4 2039 3 : 29
MTS = -206 adjust to 21394
17 4 2039 3 : 30
MTS = -206 adjust to 21394
17 4 2039 3 : 31
MTS = -206 adjust to 21394
17 4 2039 3 : 32
MTS = -206 adjust to 21394
17 4 2039 3 : 33
MTS = -206 adjust to 21394
17 4 2039 3 : 34
MTS = -206 adjust to 21394
17 4 2039 3 : 35
MTS = -206 adjust to 21394
17 4 2039 3 : 36
MTS = -206 adjust to 21394
17 4 2039 3 : 37
MTS = -206 adjust to 21394
17 4 2039 3 : 38
MTS = -206 adjust to 21394
17 4 2039 3 : 39
MTS = -206 adjust to 21394
17 4 2039 3 : 40
MTS = -206 adjust to 21394
17 4 2039 3 : 41
MTS = -206 adjust to 21394
17 4 2039 3 : 42
MTS = -206 adjust to 21394
17 4 2039 3 : 43
MTS = -206 adjust to 21394
17 4 2039 3 : 44
MTS = -206 adjust to 21394
17 4 2039 3 : 45
MTS = -206 adjust to 21394
17 4 2039 3 : 46
MTS = -206 adjust to 21394
17 4 2039 3 : 47
MTS = -206 adjust to 21394
17 4 2039 3 : 48
MTS = -206 adjust to 21394
17 4 2039 3 : 49
MTS = -206 adjust to 21394
17 4 2039 3 : 50
MTS = -206 adjust to 21394
17 4 2039 3 : 51
MTS = -206 adjust to 21394
17 4 2039 3 : 52
MTS = -206 adjust to 21394
17 4 2039 3 : 53
MTS = -205 adjust to 21395
17 4 2039 3 : 54

MTS = -205 adjust to 21395
17 4 2039 3 : 55
MTS = -205 adjust to 21395
17 4 2039 3 : 56
MTS = -205 adjust to 21395
17 4 2039 3 : 57
MTS = -205 adjust to 21395
17 4 2039 3 : 58
MTS = -205 adjust to 21395
17 4 2039 3 : 59
MTS = -205 adjust to 21395
17 4 2039 4 : 0
MTS = -205 adjust to 21395
17 4 2039 4 : 1
MTS = -205 adjust to 21395
17 4 2039 4 : 2
MTS = -205 adjust to 21395
17 4 2039 4 : 3
MTS = -205 adjust to 21395
17 4 2039 4 : 4
MTS = -205 adjust to 21395
17 4 2039 4 : 5
MTS = -205 adjust to 21395
17 4 2039 4 : 6
MTS = -205 adjust to 21395
17 4 2039 4 : 7
MTS = -205 adjust to 21395
17 4 2039 4 : 8
MTS = -205 adjust to 21395
17 4 2039 4 : 9
MTS = -205 adjust to 21395
17 4 2039 4 : 10
MTS = -205 adjust to 21395
17 4 2039 4 : 11
MTS = -205 adjust to 21395
17 4 2039 4 : 12
MTS = -205 adjust to 21395
17 4 2039 4 : 13
MTS = -205 adjust to 21395
17 4 2039 4 : 14
MTS = -205 adjust to 21395
17 4 2039 4 : 15
MTS = -205 adjust to 21395
17 4 2039 4 : 16
MTS = -205 adjust to 21395
17 4 2039 4 : 17
MTS = -205 adjust to 21395
17 4 2039 4 : 18
MTS = -205 adjust to 21395
17 4 2039 4 : 19
MTS = -204 adjust to 21396
17 4 2039 4 : 20
MTS = -204 adjust to 21396
17 4 2039 4 : 21
MTS = -204 adjust to 21396
17 4 2039 4 : 22
MTS = -204 adjust to 21396
17 4 2039 4 : 23
MTS = -204 adjust to 21396
17 4 2039 4 : 24
MTS = -204 adjust to 21396
17 4 2039 4 : 25
MTS = -204 adjust to 21396
17 4 2039 4 : 26
MTS = -204 adjust to 21396
17 4 2039 4 : 27
MTS = -204 adjust to 21396
17 4 2039 4 : 28
MTS = -204 adjust to 21396
17 4 2039 4 : 29
MTS = -204 adjust to 21396
17 4 2039 4 : 30
MTS = -204 adjust to 21396
17 4 2039 4 : 31
MTS = -204 adjust to 21396
17 4 2039 4 : 32
MTS = -204 adjust to 21396
17 4 2039 4 : 33
MTS = -204 adjust to 21396
17 4 2039 4 : 34
MTS = -204 adjust to 21396
17 4 2039 4 : 35
MTS = -204 adjust to 21396
17 4 2039 4 : 36
MTS = -204 adjust to 21396
17 4 2039 4 : 37
MTS = -204 adjust to 21396
17 4 2039 4 : 38
MTS = -204 adjust to 21396
17 4 2039 4 : 39
MTS = -204 adjust to 21396
17 4 2039 4 : 40
MTS = -204 adjust to 21396
17 4 2039 4 : 41
MTS = -204 adjust to 21396
17 4 2039 4 : 42
MTS = -204 adjust to 21396
17 4 2039 4 : 43
MTS = -204 adjust to 21396
17 4 2039 4 : 44
MTS = -203 adjust to 21397
17 4 2039 4 : 45
MTS = -203 adjust to 21397
17 4 2039 4 : 46
MTS = -203 adjust to 21397
17 4 2039 4 : 47
MTS = -203 adjust to 21397
17 4 2039 4 : 48
MTS = -203 adjust to 21397
17 4 2039 4 : 49
MTS = -203 adjust to 21397
17 4 2039 4 : 50
MTS = -203 adjust to 21397
17 4 2039 4 : 51
MTS = -203 adjust to 21397
17 4 2039 4 : 52
MTS = -203 adjust to 21397
17 4 2039 4 : 53
MTS = -203 adjust to 21397
17 4 2039 4 : 54
MTS = -203 adjust to 21397
17 4 2039 4 : 55
MTS = -203 adjust to 21397
17 4 2039 4 : 56
MTS = -203 adjust to 21397
17 4 2039 4 : 57
MTS = -203 adjust to 21397
17 4 2039 4 : 58
MTS = -203 adjust to 21397
17 4 2039 4 : 59
MTS = -203 adjust to 21397
17 4 2039 5 : 0
MTS = -203 adjust to 21397
17 4 2039 5 : 1
MTS = -203 adjust to 21397
17 4 2039 5 : 2
MTS = -203 adjust to 21397
17 4 2039 5 : 3
MTS = -203 adjust to 21397
17 4 2039 5 : 4
MTS = -203 adjust to 21397
17 4 2039 5 : 5
MTS = -203 adjust to 21397
17 4 2039 5 : 6
MTS = -203 adjust to 21397
17 4 2039 5 : 7
MTS = -203 adjust to 21397
17 4 2039 5 : 8
MTS = -203 adjust to 21397
17 4 2039 5 : 9
MTS = -202 adjust to 21398
17 4 2039 5 : 10
MTS = -202 adjust to 21398
17 4 2039 5 : 11
MTS = -202 adjust to 21398
17 4 2039 5 : 12
MTS = -202 adjust to 21398
17 4 2039 5 : 13
MTS = -202 adjust to 21398
17 4 2039 5 : 14
MTS = -202 adjust to 21398
17 4 2039 5 : 15
MTS = -202 adjust to 21398
17 4 2039 5 : 16
MTS = -202 adjust to 21398
17 4 2039 5 : 17
MTS = -202 adjust to 21398
17 4 2039 5 : 18
MTS = -202 adjust to 21398
17 4 2039 5 : 19
MTS = -202 adjust to 21398
17 4 2039 5 : 20
MTS = -202 adjust to 21398
17 4 2039 5 : 21
MTS = -202 adjust to 21398
17 4 2039 5 : 22
MTS = -202 adjust to 21398
17 4 2039 5 : 23
MTS = -202 adjust to 21398
17 4 2039 5 : 24
MTS = -202 adjust to 21398
17 4 2039 5 : 25
MTS = -202 adjust to 21398
17 4 2039 5 : 26
MTS = -202 adjust to 21398
17 4 2039 5 : 27
MTS = -202 adjust to 21398
17 4 2039 5 : 28
MTS = -202 adjust to 21398
17 4 2039 5 : 29
MTS = -202 adjust to 21398
17 4 2039 5 : 30
MTS = -202 adjust to 21398
17 4 2039 5 : 31
MTS = -202 adjust to 21398
17 4 2039 5 : 32
MTS = -202 adjust to 21398
17 4 2039 5 : 33
MTS = -202 adjust to 21398
17 4 2039 5 : 34
MTS = -201 adjust to 21399
17 4 2039 5 : 35
MTS = -201 adjust to 21399
17 4 2039 5 : 36
MTS = -201 adjust to 21399
17 4 2039 5 : 37
MTS = -201 adjust to 21399
17 4 2039 5 : 38
MTS = -201 adjust to 21399
17 4 2039 5 : 39
MTS = -201 adjust to 21399
17 4 2039 5 : 40
MTS = -201 adjust to 21399
17 4 2039 5 : 41
MTS = -201 adjust to 21399
17 4 2039 5 : 42
MTS = -201 adjust to 21399
17 4 2039 5 : 43
MTS = -201 adjust to 21399
17 4 2039 5 : 44
MTS = -201 adjust to 21399
17 4 2039 5 : 45
MTS = -201 adjust to 21399
17 4 2039 5 : 46
MTS = -201 adjust to 21399
17 4 2039 5 : 47
MTS = -201 adjust to 21399
17 4 2039 5 : 48
MTS = -201 adjust to 21399
17 4 2039 5 : 49
MTS = -201 adjust to 21399
17 4 2039 5 : 50
MTS = -201 adjust to 21399
17 4 2039 5 : 51
MTS = -201 adjust to 21399
17 4 2039 5 : 52
MTS = -201 adjust to 21399
17 4 2039 5 : 53
MTS = -201 adjust to 21399
17 4 2039 5 : 54
MTS = -201 adjust to 21399
17 4 2039 5 : 55
MTS = -201 adjust to 21399
17 4 2039 5 : 56
MTS = -201 adjust to 21399
17 4 2039 5 : 57
MTS = -201 adjust to 21399
17 4 2039 5 : 58
MTS = -201 adjust to 21399
17 4 2039 5 : 59
MTS = -200 adjust to 21400
17 4 2039 6 : 0
MTS = -200 adjust to 21400
17 4 2039 6 : 1
MTS = -200 adjust to 21400
17 4 2039 6 : 2
MTS = -200 adjust to 21400
17 4 2039 6 : 3
MTS = -200 adjust to 21400
17 4 2039 6 : 4
MTS = -200 adjust to 21400
17 4 2039 6 : 5
MTS = -200 adjust to 21400
17 4 2039 6 : 6
MTS = -200 adjust to 21400
17 4 2039 6 : 7
MTS = -200 adjust to 21400
17 4 2039 6 : 8
MTS = -200 adjust to 21400
17 4 2039 6 : 9
MTS = -200 adjust to 21400
17 4 2039 6 : 10
MTS = -200 adjust to 21400
17 4 2039 6 : 11
MTS = -200 adjust to 21400
17 4 2039 6 : 12
MTS = -200 adjust to 21400
17 4 2039 6 : 13
MTS = -200 adjust to 21400
17 4 2039 6 : 14
MTS = -200 adjust to 21400
17 4 2039 6 : 15
MTS = -200 adjust to 21400
17 4 2039 6 : 16
MTS = -200 adjust to 21400
17 4 2039 6 : 17
MTS = -200 adjust to 21400
17 4 2039 6 : 18
MTS = -200 adjust to 21400
17 4 2039 6 : 19
MTS = -200 adjust to 21400
17 4 2039 6 : 20
MTS = -200 adjust to 21400
17 4 2039 6 : 21
MTS = -200 adjust to 21400
17 4 2039 6 : 22
MTS = -200 adjust to 21400
17 4 2039 6 : 23
MTS = -200 adjust to 21400
17 4 2039 6 : 24
MTS = -200 adjust to 21400
17 4 2039 6 : 25
MTS = -199 adjust to 21401
17 4 2039 6 : 26
MTS = -199 adjust to 21401
17 4 2039 6 : 27
MTS = -199 adjust to 21401
17 4 2039 6 : 28
MTS = -199 adjust to 21401
17 4 2039 6 : 29
MTS = -199 adjust to 21401
17 4 2039 6 : 30
MTS = -199 adjust to 21401
17 4 2039 6 : 31
MTS = -199 adjust to 21401
17 4 2039 6 : 32
MTS = -199 adjust to 21401
17 4 2039 6 : 33
MTS = -199 adjust to 21401
17 4 2039 6 : 34
MTS = -199 adjust to 21401
17 4 2039 6 : 35
MTS = -199 adjust to 21401
17 4 2039 6 : 36
MTS = -199 adjust to 21401
17 4 2039 6 : 37
MTS = -199 adjust to 21401
17 4 2039 6 : 38
MTS = -199 adjust to 21401
17 4 2039 6 : 39
MTS = -199 adjust to 21401
17 4 2039 6 : 40
MTS = -199 adjust to 21401
17 4 2039 6 : 41
MTS = -199 adjust to 21401
17 4 2039 6 : 42
MTS = -199 adjust to 21401
17 4 2039 6 : 43
MTS = -199 adjust to 21401
17 4 2039 6 : 44
MTS = -199 adjust to 21401
17 4 2039 6 : 45
MTS = -199 adjust to 21401
17 4 2039 6 : 46
MTS = -199 adjust to 21401
17 4 2039 6 : 47
MTS = -199 adjust to 21401
17 4 2039 6 : 48
MTS = -199 adjust to 21401
17 4 2039 6 : 49
MTS = -199 adjust to 21401
17 4 2039 6 : 50
MTS = -198 adjust to 21402
17 4 2039 6 : 51
MTS = -198 adjust to 21402
17 4 2039 6 : 52
MTS = -198 adjust to 21402
17 4 2039 6 : 53
MTS = -198 adjust to 21402
17 4 2039 6 : 54
MTS = -198 adjust to 21402
17 4 2039 6 : 55
MTS = -198 adjust to 21402
17 4 2039 6 : 56
MTS = -198 adjust to 21402
17 4 2039 6 : 57
MTS = -198 adjust to 21402
17 4 2039 6 : 58
MTS = -198 adjust to 21402
17 4 2039 6 : 59
MTS = -198 adjust to 21402
17 4 2039 7 : 0
MTS = -198 adjust to 21402
17 4 2039 7 : 1
MTS = -198 adjust to 21402
17 4 2039 7 : 2
MTS = -198 adjust to 21402
17 4 2039 7 : 3
MTS = -198 adjust to 21402
17 4 2039 7 : 4
MTS = -198 adjust to 21402
17 4 2039 7 : 5
MTS = -198 adjust to 21402
17 4 2039 7 : 6

MTS = -198 adjust to 21402
17 4 2039 7 : 7
MTS = -198 adjust to 21402
17 4 2039 7 : 8
MTS = -198 adjust to 21402
17 4 2039 7 : 9
MTS = -198 adjust to 21402
17 4 2039 7 : 10
MTS = -198 adjust to 21402
17 4 2039 7 : 11
MTS = -198 adjust to 21402
17 4 2039 7 : 12
MTS = -198 adjust to 21402
17 4 2039 7 : 13
MTS = -198 adjust to 21402
17 4 2039 7 : 14
MTS = -198 adjust to 21402
17 4 2039 7 : 15
MTS = -197 adjust to 21403
17 4 2039 7 : 16
MTS = -197 adjust to 21403
17 4 2039 7 : 17
MTS = -197 adjust to 21403
17 4 2039 7 : 18
MTS = -197 adjust to 21403
17 4 2039 7 : 19
MTS = -197 adjust to 21403
17 4 2039 7 : 20
MTS = -197 adjust to 21403
17 4 2039 7 : 21
MTS = -197 adjust to 21403
17 4 2039 7 : 22
MTS = -197 adjust to 21403
17 4 2039 7 : 23
MTS = -197 adjust to 21403
17 4 2039 7 : 24
MTS = -197 adjust to 21403
17 4 2039 7 : 25
MTS = -197 adjust to 21403
17 4 2039 7 : 26
MTS = -197 adjust to 21403
17 4 2039 7 : 27
MTS = -197 adjust to 21403
17 4 2039 7 : 28
MTS = -197 adjust to 21403
17 4 2039 7 : 29
MTS = -197 adjust to 21403
17 4 2039 7 : 30
MTS = -197 adjust to 21403
17 4 2039 7 : 31
MTS = -197 adjust to 21403
17 4 2039 7 : 32
MTS = -197 adjust to 21403
17 4 2039 7 : 33
MTS = -197 adjust to 21403
17 4 2039 7 : 34
MTS = -197 adjust to 21403
17 4 2039 7 : 35
MTS = -197 adjust to 21403
17 4 2039 7 : 36
MTS = -197 adjust to 21403
17 4 2039 7 : 37
MTS = -197 adjust to 21403
17 4 2039 7 : 38
MTS = -197 adjust to 21403
17 4 2039 7 : 39
MTS = -197 adjust to 21403
17 4 2039 7 : 40
MTS = -196 adjust to 21404
17 4 2039 7 : 41
MTS = -196 adjust to 21404
17 4 2039 7 : 42
MTS = -196 adjust to 21404
17 4 2039 7 : 43
MTS = -196 adjust to 21404
17 4 2039 7 : 44
MTS = -196 adjust to 21404
17 4 2039 7 : 45
MTS = -196 adjust to 21404
17 4 2039 7 : 46
MTS = -196 adjust to 21404
17 4 2039 7 : 47
MTS = -196 adjust to 21404
17 4 2039 7 : 48
MTS = -196 adjust to 21404
17 4 2039 7 : 49
MTS = -196 adjust to 21404
17 4 2039 7 : 50
MTS = -196 adjust to 21404
17 4 2039 7 : 51
MTS = -196 adjust to 21404
17 4 2039 7 : 52
MTS = -196 adjust to 21404
17 4 2039 7 : 53
MTS = -196 adjust to 21404
17 4 2039 7 : 54
MTS = -196 adjust to 21404
17 4 2039 7 : 55
MTS = -196 adjust to 21404
17 4 2039 7 : 56
MTS = -196 adjust to 21404
17 4 2039 7 : 57
MTS = -196 adjust to 21404
17 4 2039 7 : 58
MTS = -196 adjust to 21404
17 4 2039 7 : 59
MTS = -196 adjust to 21404
17 4 2039 8 : 0
MTS = -196 adjust to 21404
17 4 2039 8 : 1
MTS = -196 adjust to 21404
17 4 2039 8 : 2
MTS = -196 adjust to 21404
17 4 2039 8 : 3
MTS = -196 adjust to 21404
17 4 2039 8 : 4
MTS = -196 adjust to 21404
17 4 2039 8 : 5
MTS = -195 adjust to 21405
17 4 2039 8 : 6
MTS = -195 adjust to 21405
17 4 2039 8 : 7
MTS = -195 adjust to 21405
17 4 2039 8 : 8
MTS = -195 adjust to 21405
17 4 2039 8 : 9
MTS = -195 adjust to 21405
17 4 2039 8 : 10
MTS = -195 adjust to 21405
17 4 2039 8 : 11
MTS = -195 adjust to 21405
17 4 2039 8 : 12
MTS = -195 adjust to 21405
17 4 2039 8 : 13
MTS = -195 adjust to 21405
17 4 2039 8 : 14
MTS = -195 adjust to 21405
17 4 2039 8 : 15
MTS = -195 adjust to 21405
17 4 2039 8 : 16
MTS = -195 adjust to 21405
17 4 2039 8 : 17
MTS = -195 adjust to 21405
17 4 2039 8 : 18
MTS = -195 adjust to 21405
17 4 2039 8 : 19
MTS = -195 adjust to 21405
17 4 2039 8 : 20
MTS = -195 adjust to 21405
17 4 2039 8 : 21
MTS = -195 adjust to 21405
17 4 2039 8 : 22
MTS = -195 adjust to 21405
17 4 2039 8 : 23
MTS = -195 adjust to 21405
17 4 2039 8 : 24
MTS = -195 adjust to 21405
17 4 2039 8 : 25
MTS = -195 adjust to 21405
17 4 2039 8 : 26
MTS = -195 adjust to 21405
17 4 2039 8 : 27
MTS = -195 adjust to 21405
17 4 2039 8 : 28
MTS = -195 adjust to 21405
17 4 2039 8 : 29
MTS = -195 adjust to 21405
17 4 2039 8 : 30
MTS = -195 adjust to 21405
17 4 2039 8 : 31
MTS = -194 adjust to 21406
17 4 2039 8 : 32
MTS = -194 adjust to 21406
17 4 2039 8 : 33
MTS = -194 adjust to 21406
17 4 2039 8 : 34
MTS = -194 adjust to 21406
17 4 2039 8 : 35
MTS = -194 adjust to 21406
17 4 2039 8 : 36
MTS = -194 adjust to 21406
17 4 2039 8 : 37
MTS = -194 adjust to 21406
17 4 2039 8 : 38
MTS = -194 adjust to 21406
17 4 2039 8 : 39
MTS = -194 adjust to 21406
17 4 2039 8 : 40
MTS = -194 adjust to 21406
17 4 2039 8 : 41
MTS = -194 adjust to 21406
17 4 2039 8 : 42
MTS = -194 adjust to 21406
17 4 2039 8 : 43
MTS = -194 adjust to 21406
17 4 2039 8 : 44
MTS = -194 adjust to 21406
17 4 2039 8 : 45
MTS = -194 adjust to 21406
17 4 2039 8 : 46
MTS = -194 adjust to 21406
17 4 2039 8 : 47
MTS = -194 adjust to 21406
17 4 2039 8 : 48
MTS = -194 adjust to 21406
17 4 2039 8 : 49
MTS = -194 adjust to 21406
17 4 2039 8 : 50
MTS = -194 adjust to 21406
17 4 2039 8 : 51
MTS = -194 adjust to 21406
17 4 2039 8 : 52
MTS = -194 adjust to 21406
17 4 2039 8 : 53
MTS = -194 adjust to 21406
17 4 2039 8 : 54
MTS = -194 adjust to 21406
17 4 2039 8 : 55
MTS = -194 adjust to 21406
17 4 2039 8 : 56
MTS = -193 adjust to 21407
17 4 2039 8 : 57
MTS = -193 adjust to 21407
17 4 2039 8 : 58
MTS = -193 adjust to 21407
17 4 2039 8 : 59
MTS = -193 adjust to 21407
17 4 2039 9 : 0
MTS = -193 adjust to 21407
17 4 2039 9 : 1
MTS = -193 adjust to 21407
17 4 2039 9 : 2
MTS = -193 adjust to 21407
17 4 2039 9 : 3
MTS = -193 adjust to 21407
17 4 2039 9 : 4
MTS = -193 adjust to 21407
17 4 2039 9 : 5
MTS = -193 adjust to 21407
17 4 2039 9 : 6
MTS = -193 adjust to 21407
17 4 2039 9 : 7
MTS = -193 adjust to 21407
17 4 2039 9 : 8
MTS = -193 adjust to 21407
17 4 2039 9 : 9
MTS = -193 adjust to 21407
17 4 2039 9 : 10
MTS = -193 adjust to 21407
17 4 2039 9 : 11
MTS = -193 adjust to 21407
17 4 2039 9 : 12
MTS = -193 adjust to 21407
17 4 2039 9 : 13
MTS = -193 adjust to 21407
17 4 2039 9 : 14
MTS = -193 adjust to 21407
17 4 2039 9 : 15
MTS = -193 adjust to 21407
17 4 2039 9 : 16
MTS = -193 adjust to 21407
17 4 2039 9 : 17
MTS = -193 adjust to 21407
17 4 2039 9 : 18
MTS = -193 adjust to 21407
17 4 2039 9 : 19
MTS = -193 adjust to 21407
17 4 2039 9 : 20
MTS = -193 adjust to 21407
17 4 2039 9 : 21
MTS = -191 adjust to 21409
17 4 2039 9 : 22
MTS = -191 adjust to 21409
17 4 2039 9 : 23
MTS = -191 adjust to 21409
17 4 2039 9 : 24
MTS = -191 adjust to 21409
17 4 2039 9 : 25
MTS = -191 adjust to 21409
17 4 2039 9 : 26
MTS = -191 adjust to 21409
17 4 2039 9 : 27
MTS = -191 adjust to 21409
17 4 2039 9 : 28
MTS = -191 adjust to 21409
17 4 2039 9 : 29
MTS = -191 adjust to 21409
17 4 2039 9 : 30
MTS = -191 adjust to 21409
17 4 2039 9 : 31
MTS = -191 adjust to 21409
17 4 2039 9 : 32
MTS = -191 adjust to 21409
17 4 2039 9 : 33
MTS = -191 adjust to 21409
17 4 2039 9 : 34
MTS = -191 adjust to 21409
17 4 2039 9 : 35
MTS = -191 adjust to 21409
17 4 2039 9 : 36
MTS = -191 adjust to 21409
17 4 2039 9 : 37
MTS = -191 adjust to 21409
17 4 2039 9 : 38
MTS = -191 adjust to 21409
17 4 2039 9 : 39
MTS = -191 adjust to 21409
17 4 2039 9 : 40
MTS = -191 adjust to 21409
17 4 2039 9 : 41
MTS = -191 adjust to 21409
17 4 2039 9 : 42
MTS = -191 adjust to 21409
17 4 2039 9 : 43
MTS = -191 adjust to 21409
17 4 2039 9 : 44
MTS = -191 adjust to 21409
17 4 2039 9 : 45
MTS = -191 adjust to 21409
17 4 2039 9 : 46
MTS = -190 adjust to 21410
17 4 2039 9 : 47
MTS = -190 adjust to 21410
17 4 2039 9 : 48
MTS = -190 adjust to 21410
17 4 2039 9 : 49
MTS = -190 adjust to 21410
17 4 2039 9 : 50
MTS = -190 adjust to 21410
17 4 2039 9 : 51
MTS = -190 adjust to 21410
17 4 2039 9 : 52
MTS = -190 adjust to 21410
17 4 2039 9 : 53
MTS = -190 adjust to 21410
17 4 2039 9 : 54
MTS = -190 adjust to 21410
17 4 2039 9 : 55
MTS = -190 adjust to 21410
17 4 2039 9 : 56
MTS = -190 adjust to 21410
17 4 2039 9 : 57
MTS = -190 adjust to 21410
17 4 2039 9 : 58
MTS = -190 adjust to 21410
17 4 2039 9 : 59
MTS = -190 adjust to 21410
17 4 2039 10 : 0
MTS = -190 adjust to 21410
17 4 2039 10 : 1
MTS = -190 adjust to 21410
17 4 2039 10 : 2
MTS = -190 adjust to 21410
17 4 2039 10 : 3
MTS = -190 adjust to 21410
17 4 2039 10 : 4
MTS = -190 adjust to 21410
17 4 2039 10 : 5
MTS = -190 adjust to 21410
17 4 2039 10 : 6
MTS = -190 adjust to 21410
17 4 2039 10 : 7
MTS = -190 adjust to 21410
17 4 2039 10 : 8
MTS = -190 adjust to 21410
17 4 2039 10 : 9
MTS = -190 adjust to 21410
17 4 2039 10 : 10
MTS = -190 adjust to 21410
17 4 2039 10 : 11
MTS = -189 adjust to 21411
17 4 2039 10 : 12
MTS = -189 adjust to 21411
17 4 2039 10 : 13
MTS = -189 adjust to 21411
17 4 2039 10 : 14
MTS = -189 adjust to 21411
17 4 2039 10 : 15
MTS = -189 adjust to 21411
17 4 2039 10 : 16
MTS = -189 adjust to 21411
17 4 2039 10 : 17

MTS = -189 adjust to 21411
17 4 2039 10 : 18
MTS = -189 adjust to 21411
17 4 2039 10 : 19
MTS = -189 adjust to 21411
17 4 2039 10 : 20
MTS = -189 adjust to 21411
17 4 2039 10 : 21
MTS = -189 adjust to 21411
17 4 2039 10 : 22
MTS = -189 adjust to 21411
17 4 2039 10 : 23
MTS = -189 adjust to 21411
17 4 2039 10 : 24
MTS = -189 adjust to 21411
17 4 2039 10 : 25
MTS = -189 adjust to 21411
17 4 2039 10 : 26
MTS = -189 adjust to 21411
17 4 2039 10 : 27
MTS = -189 adjust to 21411
17 4 2039 10 : 28
MTS = -189 adjust to 21411
17 4 2039 10 : 29
MTS = -189 adjust to 21411
17 4 2039 10 : 30
MTS = -189 adjust to 21411
17 4 2039 10 : 31
MTS = -189 adjust to 21411
17 4 2039 10 : 32
MTS = -189 adjust to 21411
17 4 2039 10 : 33
MTS = -189 adjust to 21411
17 4 2039 10 : 34
MTS = -189 adjust to 21411
17 4 2039 10 : 35
MTS = -189 adjust to 21411
17 4 2039 10 : 36
MTS = -189 adjust to 21411
17 4 2039 10 : 37
MTS = -188 adjust to 21412
17 4 2039 10 : 38
MTS = -188 adjust to 21412
17 4 2039 10 : 39
MTS = -188 adjust to 21412
17 4 2039 10 : 40
MTS = -188 adjust to 21412
17 4 2039 10 : 41
MTS = -188 adjust to 21412
17 4 2039 10 : 42
MTS = -188 adjust to 21412
17 4 2039 10 : 43
MTS = -188 adjust to 21412
17 4 2039 10 : 44
MTS = -188 adjust to 21412
17 4 2039 10 : 45
MTS = -188 adjust to 21412
17 4 2039 10 : 46
MTS = -188 adjust to 21412
17 4 2039 10 : 47
MTS = -188 adjust to 21412
17 4 2039 10 : 48
MTS = -188 adjust to 21412
17 4 2039 10 : 49
MTS = -188 adjust to 21412
17 4 2039 10 : 50
MTS = -188 adjust to 21412
17 4 2039 10 : 51
MTS = -188 adjust to 21412
17 4 2039 10 : 52
MTS = -188 adjust to 21412
17 4 2039 10 : 53
MTS = -188 adjust to 21412
17 4 2039 10 : 54
MTS = -188 adjust to 21412
17 4 2039 10 : 55
MTS = -188 adjust to 21412
17 4 2039 10 : 56
MTS = -188 adjust to 21412
17 4 2039 10 : 57
MTS = -188 adjust to 21412
17 4 2039 10 : 58
MTS = -188 adjust to 21412
17 4 2039 10 : 59
MTS = -188 adjust to 21412
17 4 2039 11 : 0
MTS = -188 adjust to 21412
17 4 2039 11 : 1
MTS = -188 adjust to 21412
17 4 2039 11 : 2
MTS = -187 adjust to 21413
17 4 2039 11 : 3
MTS = -187 adjust to 21413
17 4 2039 11 : 4
MTS = -187 adjust to 21413
17 4 2039 11 : 5
MTS = -187 adjust to 21413
17 4 2039 11 : 6
MTS = -187 adjust to 21413
17 4 2039 11 : 7
MTS = -187 adjust to 21413
17 4 2039 11 : 8
MTS = -187 adjust to 21413
17 4 2039 11 : 9
MTS = -187 adjust to 21413
17 4 2039 11 : 10
MTS = -187 adjust to 21413
17 4 2039 11 : 11
MTS = -187 adjust to 21413
17 4 2039 11 : 12
MTS = -187 adjust to 21413
17 4 2039 11 : 13
MTS = -187 adjust to 21413
17 4 2039 11 : 14
MTS = -187 adjust to 21413
17 4 2039 11 : 15
MTS = -187 adjust to 21413
17 4 2039 11 : 16
MTS = -187 adjust to 21413
17 4 2039 11 : 17
MTS = -187 adjust to 21413
17 4 2039 11 : 18
MTS = -187 adjust to 21413
17 4 2039 11 : 19
MTS = -187 adjust to 21413
17 4 2039 11 : 20
MTS = -187 adjust to 21413
17 4 2039 11 : 21
MTS = -187 adjust to 21413
17 4 2039 11 : 22
MTS = -187 adjust to 21413
17 4 2039 11 : 23
MTS = -187 adjust to 21413
17 4 2039 11 : 24
MTS = -187 adjust to 21413
17 4 2039 11 : 25
MTS = -187 adjust to 21413
17 4 2039 11 : 26
MTS = -187 adjust to 21413
17 4 2039 11 : 27
MTS = -186 adjust to 21414
17 4 2039 11 : 28
MTS = -186 adjust to 21414
17 4 2039 11 : 29
MTS = -186 adjust to 21414
17 4 2039 11 : 30
MTS = -186 adjust to 21414
17 4 2039 11 : 31
MTS = -186 adjust to 21414
17 4 2039 11 : 32
MTS = -186 adjust to 21414
17 4 2039 11 : 33
MTS = -186 adjust to 21414
17 4 2039 11 : 34
MTS = -186 adjust to 21414
17 4 2039 11 : 35
MTS = -186 adjust to 21414
17 4 2039 11 : 36
MTS = -186 adjust to 21414
17 4 2039 11 : 37
MTS = -186 adjust to 21414
17 4 2039 11 : 38
MTS = -186 adjust to 21414
17 4 2039 11 : 39
MTS = -186 adjust to 21414
17 4 2039 11 : 40
MTS = -186 adjust to 21414
17 4 2039 11 : 41
MTS = -186 adjust to 21414
17 4 2039 11 : 42
MTS = -186 adjust to 21414
17 4 2039 11 : 43
MTS = -186 adjust to 21414
17 4 2039 11 : 44
MTS = -186 adjust to 21414
17 4 2039 11 : 45
MTS = -186 adjust to 21414
17 4 2039 11 : 46
MTS = -186 adjust to 21414
17 4 2039 11 : 47
MTS = -186 adjust to 21414
17 4 2039 11 : 48
MTS = -186 adjust to 21414
17 4 2039 11 : 49
MTS = -186 adjust to 21414
17 4 2039 11 : 50
MTS = -186 adjust to 21414
17 4 2039 11 : 51
MTS = -186 adjust to 21414
17 4 2039 11 : 52
MTS = -185 adjust to 21415
17 4 2039 11 : 53
MTS = -185 adjust to 21415
17 4 2039 11 : 54
MTS = -185 adjust to 21415
17 4 2039 11 : 55
MTS = -185 adjust to 21415
17 4 2039 11 : 56
MTS = -185 adjust to 21415
17 4 2039 11 : 57
MTS = -185 adjust to 21415
17 4 2039 11 : 58
MTS = -185 adjust to 21415
17 4 2039 11 : 59
MTS = -185 adjust to 21415
17 4 2039 12 : 0
MTS = -185 adjust to 21415
17 4 2039 12 : 1
MTS = -185 adjust to 21415
17 4 2039 12 : 2
MTS = -185 adjust to 21415
17 4 2039 12 : 3
MTS = -185 adjust to 21415
17 4 2039 12 : 4
MTS = -185 adjust to 21415
17 4 2039 12 : 5
MTS = -185 adjust to 21415
17 4 2039 12 : 6
MTS = -185 adjust to 21415
17 4 2039 12 : 7
MTS = -185 adjust to 21415
17 4 2039 12 : 8
MTS = -185 adjust to 21415
17 4 2039 12 : 9
MTS = -185 adjust to 21415
17 4 2039 12 : 10
MTS = -185 adjust to 21415
17 4 2039 12 : 11
MTS = -185 adjust to 21415
17 4 2039 12 : 12
MTS = -185 adjust to 21415
17 4 2039 12 : 13
MTS = -185 adjust to 21415
17 4 2039 12 : 14
MTS = -185 adjust to 21415
17 4 2039 12 : 15
MTS = -185 adjust to 21415
17 4 2039 12 : 16
MTS = -185 adjust to 21415
17 4 2039 12 : 17
MTS = -184 adjust to 21416
17 4 2039 12 : 18
MTS = -184 adjust to 21416
17 4 2039 12 : 19
MTS = -184 adjust to 21416
17 4 2039 12 : 20
MTS = -184 adjust to 21416
17 4 2039 12 : 21
MTS = -184 adjust to 21416
17 4 2039 12 : 22
MTS = -184 adjust to 21416
17 4 2039 12 : 23
MTS = -184 adjust to 21416
17 4 2039 12 : 24
MTS = -184 adjust to 21416
17 4 2039 12 : 25
MTS = -184 adjust to 21416
17 4 2039 12 : 26
MTS = -184 adjust to 21416
17 4 2039 12 : 27
MTS = -184 adjust to 21416
17 4 2039 12 : 28
MTS = -184 adjust to 21416
17 4 2039 12 : 29
MTS = -184 adjust to 21416
17 4 2039 12 : 30
MTS = -184 adjust to 21416
17 4 2039 12 : 31
MTS = -184 adjust to 21416
17 4 2039 12 : 32
MTS = -184 adjust to 21416
17 4 2039 12 : 33
MTS = -184 adjust to 21416
17 4 2039 12 : 34
MTS = -184 adjust to 21416
17 4 2039 12 : 35
MTS = -184 adjust to 21416
17 4 2039 12 : 36
MTS = -184 adjust to 21416
17 4 2039 12 : 37
MTS = -184 adjust to 21416
17 4 2039 12 : 38
MTS = -184 adjust to 21416
17 4 2039 12 : 39
MTS = -184 adjust to 21416
17 4 2039 12 : 40
MTS = -184 adjust to 21416
17 4 2039 12 : 41
MTS = -184 adjust to 21416
17 4 2039 12 : 42
MTS = -184 adjust to 21416
17 4 2039 12 : 43
MTS = -183 adjust to 21417
17 4 2039 12 : 44
MTS = -183 adjust to 21417
17 4 2039 12 : 45
MTS = -183 adjust to 21417
17 4 2039 12 : 46
MTS = -183 adjust to 21417
17 4 2039 12 : 47
MTS = -183 adjust to 21417
17 4 2039 12 : 48
MTS = -183 adjust to 21417
17 4 2039 12 : 49
MTS = -183 adjust to 21417
17 4 2039 12 : 50
MTS = -183 adjust to 21417
17 4 2039 12 : 51
MTS = -183 adjust to 21417
17 4 2039 12 : 52
MTS = -183 adjust to 21417
17 4 2039 12 : 53
MTS = -183 adjust to 21417
17 4 2039 12 : 54
MTS = -183 adjust to 21417
17 4 2039 12 : 55
MTS = -183 adjust to 21417
17 4 2039 12 : 56
MTS = -183 adjust to 21417
17 4 2039 12 : 57
MTS = -183 adjust to 21417
17 4 2039 12 : 58
MTS = -183 adjust to 21417
17 4 2039 12 : 59
MTS = -183 adjust to 21417
17 4 2039 13 : 0
MTS = -183 adjust to 21417
17 4 2039 13 : 1
MTS = -183 adjust to 21417
17 4 2039 13 : 2
MTS = -183 adjust to 21417
17 4 2039 13 : 3
MTS = -183 adjust to 21417
17 4 2039 13 : 4
MTS = -183 adjust to 21417
17 4 2039 13 : 5
MTS = -183 adjust to 21417
17 4 2039 13 : 6
MTS = -183 adjust to 21417
17 4 2039 13 : 7
MTS = -183 adjust to 21417
17 4 2039 13 : 8
MTS = -182 adjust to 21418
17 4 2039 13 : 9
MTS = -182 adjust to 21418
17 4 2039 13 : 10
MTS = -182 adjust to 21418
17 4 2039 13 : 11
MTS = -182 adjust to 21418
17 4 2039 13 : 12
MTS = -182 adjust to 21418
17 4 2039 13 : 13
MTS = -182 adjust to 21418
17 4 2039 13 : 14
MTS = -182 adjust to 21418
17 4 2039 13 : 15
MTS = -182 adjust to 21418
17 4 2039 13 : 16
MTS = -182 adjust to 21418
17 4 2039 13 : 17
MTS = -182 adjust to 21418
17 4 2039 13 : 18
MTS = -182 adjust to 21418
17 4 2039 13 : 19
MTS = -182 adjust to 21418
17 4 2039 13 : 20
MTS = -182 adjust to 21418
17 4 2039 13 : 21
MTS = -182 adjust to 21418
17 4 2039 13 : 22
MTS = -182 adjust to 21418
17 4 2039 13 : 23
MTS = -182 adjust to 21418
17 4 2039 13 : 24
MTS = -182 adjust to 21418
17 4 2039 13 : 25

MTS = -182 adjust to 21418
17 4 2039 13 : 26
MTS = -182 adjust to 21418
17 4 2039 13 : 27
MTS = -182 adjust to 21418
17 4 2039 13 : 28
MTS = -182 adjust to 21418
17 4 2039 13 : 29
MTS = -182 adjust to 21418
17 4 2039 13 : 30
MTS = -182 adjust to 21418
17 4 2039 13 : 31
MTS = -182 adjust to 21418
17 4 2039 13 : 32
MTS = -182 adjust to 21418
17 4 2039 13 : 33
MTS = -181 adjust to 21419
17 4 2039 13 : 34
MTS = -181 adjust to 21419
17 4 2039 13 : 35
MTS = -181 adjust to 21419
17 4 2039 13 : 36
MTS = -181 adjust to 21419
17 4 2039 13 : 37
MTS = -181 adjust to 21419
17 4 2039 13 : 38
MTS = -181 adjust to 21419
17 4 2039 13 : 39
MTS = -181 adjust to 21419
17 4 2039 13 : 40
MTS = -181 adjust to 21419
17 4 2039 13 : 41
MTS = -181 adjust to 21419
17 4 2039 13 : 42
MTS = -181 adjust to 21419
17 4 2039 13 : 43
MTS = -181 adjust to 21419
17 4 2039 13 : 44
MTS = -181 adjust to 21419
17 4 2039 13 : 45
MTS = -181 adjust to 21419
17 4 2039 13 : 46
MTS = -181 adjust to 21419
17 4 2039 13 : 47
MTS = -181 adjust to 21419
17 4 2039 13 : 48
MTS = -181 adjust to 21419
17 4 2039 13 : 49
MTS = -181 adjust to 21419
17 4 2039 13 : 50
MTS = -181 adjust to 21419
17 4 2039 13 : 51
MTS = -181 adjust to 21419
17 4 2039 13 : 52
MTS = -181 adjust to 21419
17 4 2039 13 : 53
MTS = -181 adjust to 21419
17 4 2039 13 : 54
MTS = -181 adjust to 21419
17 4 2039 13 : 55
MTS = -181 adjust to 21419
17 4 2039 13 : 56
MTS = -181 adjust to 21419
17 4 2039 13 : 57
MTS = -181 adjust to 21419
17 4 2039 13 : 58
MTS = -180 adjust to 21420
17 4 2039 13 : 59
MTS = -180 adjust to 21420
17 4 2039 14 : 0
MTS = -180 adjust to 21420
17 4 2039 14 : 1
MTS = -180 adjust to 21420
17 4 2039 14 : 2
MTS = -180 adjust to 21420
17 4 2039 14 : 3
MTS = -180 adjust to 21420
17 4 2039 14 : 4
MTS = -180 adjust to 21420
17 4 2039 14 : 5
MTS = -180 adjust to 21420
17 4 2039 14 : 6
MTS = -180 adjust to 21420
17 4 2039 14 : 7
MTS = -180 adjust to 21420
17 4 2039 14 : 8
MTS = -180 adjust to 21420
17 4 2039 14 : 9
MTS = -180 adjust to 21420
17 4 2039 14 : 10
MTS = -180 adjust to 21420
17 4 2039 14 : 11
MTS = -180 adjust to 21420
17 4 2039 14 : 12
MTS = -180 adjust to 21420
17 4 2039 14 : 13
MTS = -180 adjust to 21420
17 4 2039 14 : 14
MTS = -180 adjust to 21420
17 4 2039 14 : 15
MTS = -180 adjust to 21420
17 4 2039 14 : 16
MTS = -180 adjust to 21420
17 4 2039 14 : 17
MTS = -180 adjust to 21420
17 4 2039 14 : 18
MTS = -180 adjust to 21420
17 4 2039 14 : 19
MTS = -180 adjust to 21420
17 4 2039 14 : 20
MTS = -180 adjust to 21420
17 4 2039 14 : 21
MTS = -180 adjust to 21420
17 4 2039 14 : 22
MTS = -180 adjust to 21420
17 4 2039 14 : 23
MTS = -179 adjust to 21421
17 4 2039 14 : 24
MTS = -179 adjust to 21421
17 4 2039 14 : 25
MTS = -179 adjust to 21421
17 4 2039 14 : 26
MTS = -179 adjust to 21421
17 4 2039 14 : 27
MTS = -179 adjust to 21421
17 4 2039 14 : 28
MTS = -179 adjust to 21421
17 4 2039 14 : 29
MTS = -179 adjust to 21421
17 4 2039 14 : 30
MTS = -179 adjust to 21421
17 4 2039 14 : 31
MTS = -179 adjust to 21421
17 4 2039 14 : 32
MTS = -179 adjust to 21421
17 4 2039 14 : 33
MTS = -179 adjust to 21421
17 4 2039 14 : 34
MTS = -179 adjust to 21421
17 4 2039 14 : 35
MTS = -179 adjust to 21421
17 4 2039 14 : 36
MTS = -179 adjust to 21421
17 4 2039 14 : 37
MTS = -179 adjust to 21421
17 4 2039 14 : 38
MTS = -179 adjust to 21421
17 4 2039 14 : 39

In [8]:
df1 = df[['dt','dtny','ahra','jultin','kj','aw','masG','dT','au','van',
         'stin','sec','ahra_','kj_','aw_','masG_','dT_','au_','van_',
         'mathasun','pholsun','SPholGA','SKhan','SPushlip','SJyaGA','ravipphol','sun',
         'mtu','mathamoon','uv','MPholGA','MKhan','MPushlip','MJyaGA','chandraphol','moon',
         'rahu','geth','mars','mercury','venus','jupiter','saturn','uranus',
         'sun_Z','sun_D','sun_M',
         'moon_Z','moon_D','moon_M',
         'rahu_Z','rahu_D','rahu_M',
         'geth_Z','geth_D','geth_M',
         'mars_Z','mars_D','mars_M',
         'mercury_Z','mercury_D','mercury_M',
         'venus_Z','venus_D','venus_M',
         'jupiter_Z','jupiter_D','jupiter_M',
         'saturn_Z','saturn_D','saturn_M',
         'uranus_Z','uranus_D','uranus_M',
        ]]
df1.to_csv(r"C:\Users\JACK\Desktop\S_out.csv")

In [73]:
df1 = df[['dt','dtny','ahra','jultin','kj','aw','masG','dT','au','van',
         'stin','sec','ahra_','kj_','aw_','masG_','dT_','au_','van_',
         'sun','moon','rahu','geth','mars','mercury','venus','jupiter','saturn','uranus',
         'sun_Z','sun_D','sun_M',
         'moon_Z','moon_D','moon_M',
         'rahu_Z','rahu_D','rahu_M',
         'geth_Z','geth_D','geth_M',
         'mars_Z','mars_D','mars_M',
         'mercury_Z','mercury_D','mercury_M',
         'venus_Z','venus_D','venus_M',
         'jupiter_Z','jupiter_D','jupiter_M',
         'saturn_Z','saturn_D','saturn_M',
         'uranus_Z','uranus_D','uranus_M',
         
         'mathasun'
        ]]
df1.to_csv(r"C:\Users\JACK\Desktop\S_out.csv")

In [35]:
df2 = df[['dt','kj_','mathasun',
         'sun',
         'sun_Z','sun_D','sun_M'
        ]]
df2.to_csv(r"C:\Users\JACK\Desktop\S_out_before.csv")

In [4]:
dt1= datetime(2019,1,1,0,0)
dt2= datetime(1943,4,17,9,49)
dt3= datetime(2019,1,2,22,45)


test1= hora(dt1)
test2= hora(dt2)
test3= hora(dt3)

#Create dataframe
#Method1
data = {
    'dt': [dt1,dt2,dt3],
    'sun' : [test1.sun,test2.sun,test3.sun],
    'moon': [test1.moon,test2.moon,test3.moon],
    'rahu' : [test1.rahu,test2.rahu,test3.rahu],
    'geth' : [test1.geth,test2.geth,test3.geth],
    'mars' : [test1.mars,test2.mars,test3.mars],
    'mercury' : [test1.mercury,test2.mercury,test3.mercury],
    'venus' : [test1.venus,test2.venus,test3.venus],
    'jupiter' : [test1.jupiter,test2.jupiter,test3.jupiter],
    'saturn' : [test1.saturn,test2.saturn,test3.saturn],
    'uranus' : [test1.uranus,test2.uranus,test3.uranus]
}


#Method2
# data = [
#     {'dt': dt1, 'ssun': test1.sun, 'smoon': test1.moon},
#     {'dt': dt2, 'ssun': test2.sun, 'smoon': test2.moon},
#     {'dt': dt3, 'ssun': test3.sun, 'smoon': test3.moon},
# ]

df = pd.DataFrame(data)


loops = ['sun','moon','rahu','geth','mars','mercury','venus','jupiter','saturn','uranus'] 

for planet in loops:
    zodiac = planet+"_Z"
    degree = planet+"_D"
    minute = planet+"_M"
    df[zodiac] =  df[planet]//1800 
    df[degree] =  (df[planet]%1800)//60 
    df[minute] =  (df[planet]%1800)%60

# df['sun_Z'] =  df['ssun']//1800 
# df['sun_D'] =  (df['ssun']%1800)//60 
# df['sun_M'] =  (df['ssun']%1800)%60

df[['sun_Z','sun_D','sun_M','moon_Z','moon_D','moon_M','rahu_Z','rahu_D','rahu_M','geth_Z','geth_D','geth_M']]
#df[['mercury_Z','mercury_D','mercury_M','venus_Z','venus_D','venus_M']]
#df[['mars_Z','mars_D','mars_M','jupiter_Z','jupiter_D','jupiter_M','saturn_Z','saturn_D','saturn_M','uranus_Z','uranus_D','uranus_M']]

Smars = -1498 adjust to 20102
MTS = -137 adjust to 21463
SMercury = 22715 adjust to 1115
Smars = -1431 adjust to 20169

,sun_Z,sun_D,sun_M,moon_Z,moon_D,moon_M,rahu_Z,rahu_D,rahu_M,geth_Z,geth_D,geth_M
0,8,15,29,6,13,42,3,2,45,9,7,50
1,0,3,21,4,25,31,3,28,19,5,29,0
2,8,17,29,7,9,51,3,2,39,9,6,48

In [13]:
dt1= datetime(1984,1,27,9,49)
dt2= datetime(2007,3,30,8,55)
dt3= datetime(2010,1,27,22,52)


test1= hora(dt1)
test2= hora(dt2)
test3= hora(dt3)

#Create dataframe
#Method1
data = {
    'dt': [dt1,dt2,dt3],
    'ssun' : [test1.sun,test2.sun,test3.sun],
    'smoon': [test1.moon,test2.moon,test3.moon],
    'srahu' : [test1.rahu,test2.rahu,test3.rahu],
    'sgeth' : [test1.geth,test2.geth,test3.geth],
    'smars' : [test1.mars,test2.mars,test3.mars],
    'smercury' : [test1.mercury,test2.mercury,test3.mercury],
    'svenus' : [test1.venus,test2.venus,test3.venus],
    'jupiter' : [test1.jupiter,test2.jupiter,test3.jupiter],
    'ssaturn' : [test1.saturn,test2.saturn,test3.saturn],
    'suranus' : [test1.uranus,test2.uranus,test3.uranus]
}


#Method2
# data = [
#     {'dt': dt1, 'ssun': test1.sun, 'smoon': test1.moon},
#     {'dt': dt2, 'ssun': test2.sun, 'smoon': test2.moon},
#     {'dt': dt3, 'ssun': test3.sun, 'smoon': test3.moon},
# ]

df = pd.DataFrame(data)



#Add row to DataFrame
#METHOD1: add or update specify by row name 
#df.loc[2] = [dt3,10,20]
#df.loc[3] = [dt3,10,20]

#METHOD1.1: Add row to the end of dataframe 
#df.loc[len(df.index)] = [dt3,10,20]
#df.loc[len(df.index)] = [dt3,10,20]
# df.loc[len(df.index)] = [dt3,10,20]


#METHOD2: Add row to some columns
#df = df.append({'dt' : 'dateadded' , 'ssun' : 2222} , ignore_index=True)

#print(len(df.index))


#Change column name
#df.columns = 'a','b','c'

#create new column and data
#method1
#df['newcolumn1'] = ''
#df['newcolumn1'] = [1,2,3,4,5]

#Method2
#df.insert(4, "newcolumn2", [21, 23, 24, 21, 20], True) 
#df.insert(len(df.columns), "newcolumn2", [21, 23, 24, 21, 20], True) 

#Method3-Create new 
#df2 = df.assign(address = ['Delhi', 'Bangalore', 'Chennai', 'Patna', 'ddd']) 
#df2


#Drop column 
#df = df.drop(columns=['newcolumn1','newcolumn2'])


# df['sun_Z'] =  df['ssun']//1800 
# df['sun_D'] =  (df['ssun']%1800)//60 
# df['sun_M'] =  (df['ssun']%1800)%60

# df['moon_Z'] =  df['smoon']//1800 
# df['moon_D'] =  (df['smoon']%1800)//60 
# df['moon_M'] =  (df['smoon']%1800)%60

# df['rahu_Z'] =  df['srahu']//1800 
# df['rahu_D'] =  (df['srahu']%1800)//60 
# df['rahu_M'] =  (df['srahu']%1800)%60

# df['geth_Z'] =  df['sgeth']//1800 
# df['geth_D'] =  (df['sgeth']%1800)//60 
# df['geth_M'] =  (df['sgeth']%1800)%60

# df['mars_Z'] =  df['smars']//1800 
# df['mars_D'] =  (df['smars']%1800)//60 
# df['mars_M'] =  (df['smars']%1800)%60



# df[0:]




#sliding rows 
#df[2:3]

#sliding columns 
# df[['dt','ssun','smoon']]

#sliding rows and columns 
#df.loc[row,colmm]
# df.loc[:,:]
# df.loc[1,['dt']]
# df.loc[1:3,['dt','ssun','smoon']]
# df.loc[1:3,'dt':'ssun']

#Change index
# df.set_index("dt", inplace=True)
# df.loc[:,:]
# df.loc[dt1,:]
# df.loc[dt1:dt3,['ssun','smoon']]
# df.loc[dt1:dt3,'ssun':'ssun_m']

#boolean
# df.loc[df['smoon'] >= 7000,'ssun':'ssun_m']

df



#df.loc[0:3,'dt']>dt1
#df.loc[0:3,'dt']>dt1
#data.set_index("last_name", inplace=True)

uv = 14819
pholGA = 4019
khan = 4
SVenus = 22652 adjust to 1052
uv = 17719
pholGA = 3881
khan = 4
uv = 7926
pholGA = 2874
khan = 3

,dt,ssun,smoon,srahu,sgeth,smars,smercury,svenus,jupiter,ssaturn,suranus
0,1984-01-27 09:49:00,16953,12913,2933,12108,11722,15638,14765,14973,11999,13324
1,2007-03-30 08:55:00,20702,7569,19222,2089,18000,19459,1052,14290,6638,19352
2,2010-01-27 22:52:00,17003,4207,15932,12377,6532,15557,17071,18534,9464,19983

In [38]:
#df[['dt','ssun','sun_Z','sun_D','sun_M','smoon','moon_Z','moon_D','moon_M']]

In [39]:
# s_ravi = {
#     'jya': [35,32,27,22,13,5],
#     'ravi': [0,35,67,94,116,129]
# }
# #df = pd.DataFrame(s_ravi)
# df = pd.DataFrame(s_ravi)
# #df.iloc[1] = [kj,Ssun]
# #df.append(data)
# df = df.append({'kj' : 'Sahil' , 'sun' : 22} , ignore_index=True)
# df = df.append({'kj' : 'Sahil' , 'sun' : 22} , ignore_index=True)

# df = df.append({'kj' : 'Sahil' , 'sun' : 22 , 'datetime' : dt} , ignore_index=True)
# df = df.append({'kj' : 'Sahil' , 'sun' : 22 , 'datetime' : dtny} , ignore_index=True)


#Create dataframe
df = pd.DataFrame()

# Creating an empty Dataframe with column names only
df = pd.DataFrame(columns=['User_ID', 'UserName', 'Action'])

# Create an empty Dataframe with columns or indices
#df = pd.DataFrame(columns=['User_ID', 'UserName', 'Action'], index=['a', 'b', 'c'])

print(df.head(5))
print(df.tail())

print(df.dtypes)
print(df.index)
print(df.columns)
print(df.values)

#for index,row in df.iterrows():
#    print (index, row['ssun'], row['smoon'])

Empty DataFrame
Columns: [User_ID, UserName, Action]
Index: []
Empty DataFrame
Columns: [User_ID, UserName, Action]
Index: []
User_ID     object
UserName    object
Action      object
dtype: object
Index([], dtype='object')
Index(['User_ID', 'UserName', 'Action'], dtype='object')
[]

In [8]:
day,month,year,hour,minute = 27,1,2527,9,49
christ_year = year-543

dt= datetime(christ_year,month,day,hour,minute)

a = hora(dt)  
print('dt =', a.dt)
print('dtnt =', a.dtny)
print('ahra =', a.ahra)
print('jultin =', a.jultin)
print('kj =', a.kj)
print('aw =', a.aw)
print('masG =', a.masG)
print('dT =', a.dT)
print('au =', a.au)
print('van =', a.van)

print('stin =', a.stin)
print('sec =', a.sec)
print('ahra_ =', a.ahra_)
print('kj_ =', a.kj_)
print('aw_ =', a.aw_)
print('masG_ =', a.masG_)
print('dT_ =', a.dT_)
print('au_ =', a.au_)
print('van_ =', a.van_)

print('sun =', a.sun)
print('moon =', a.moon)
print('rahu =', a.rahu)
print('geth =', a.geth)
print('mars =', a.mars)
print('mercury =', a.mercury)
print('venus =', a.venus)
print('jupiter =', a.jupiter)
print('saturn =', a.saturn)
print('uranus =', a.uranus)

dt = 1984-01-27 09:31:00
dtnt = 1983-04-16 11:38:24
ahra = 491274
jultin = 388
kj = 412
aw = 144
masG = 16636
dT = 4
au = 2621
van = 0
stin = 286
sec = 34260
ahra_ = 491560
kj_ = 228729
aw_ = 97
masG_ = 16645
dT_ = 24
au_ = 2907
van_ = 6
sun = 16953
moon = 12913
rahu = 2933
geth = 12108
mars = 11722
mercury = 15638
venus = 14765
jupiter = 14973
saturn = 11999
uranus = 13324

#